### ISSUE TITLE
Cosmology modules: Memory leak if module path is changed manually after installation

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [CobayaSampler/cobaya#10]
I install cobaya and use `cobaya-install cosmo -m /home/stefan/modules` to install the modules. I can run cobaya using the code generated by `cobaya-cosmo-generator` (see code below) without problems.
Now I move the modules to a different folder (to a faster drive in my case) and change the 'modules' value in the info dict. When I run cobaya now, the output is is at 

    Sampling! (NB: nothing will be printed until 120 burn-in samples have been obtained)

and the python process uses increasingly more RAM. `strace python cosmo.py` shows

    openat(AT_FDCWD, "/home/stefan/modules/code/classy/bbn/sBBN_2017.dat", O_RDONLY) = -1 ENOENT (No such file or directory)

many times. Cobaya somehow still uses the old location for the modules and allocates lots of memory (my system hung up at 28G during lunch).

**How to reproduce:**
Rename your cobaya modules folder, change it in the yaml file / info dict and run some cosmology.

**Expected behaviour:**
It would be nice if cobaya could show a warning/error if this happens and tell the user where to change the module path (or use the correct path automatically).

I used python3 and different likelihoods and had that with every likelihood problem.
I also tested it on Scientific Linux 7.5 with python2 and gcc version < 5.

Edit: **Workaround**:
If one deletes the module folder and runs `cobaya-install` again (with the new path), everything works again.

Example code, mostly generated by cobaya-cosmo-generator:

    import cobaya.run as cbyr
    from collections import OrderedDict

    info = {
    'modules': '/home/stefan/modules_new/',
    'output': 'chains/cosmo',
    'force': True,
    'likelihood': OrderedDict([
                                ('sixdf_2011_bao', None),
                              ]),
     'params': OrderedDict([('logA',
                             OrderedDict([('prior',
                                           OrderedDict([('min', 2), ('max', 4)])),
                                          ('ref',
                                           OrderedDict([('dist', 'norm'),
                                                        ('loc', 3.1),
                                                        ('scale', 0.001)])),
                                          ('proposal', 0.001),
                                          ('latex', '\\log(10^{10} A_\\mathrm{s})'),
                                          ('drop', True)])),
                            ('A_s',
                             OrderedDict([('value',
                                           'lambda logA: 1e-10*np.exp(logA)'),
                                          ('latex', 'A_\\mathrm{s}')])),
                            ('n_s',
                             OrderedDict([('prior',
                                           OrderedDict([('min', 0.8),
                                                        ('max', 1.2)])),
                                          ('ref',
                                           OrderedDict([('dist', 'norm'),
                                                        ('loc', 0.96),
                                                        ('scale', 0.004)])),
                                          ('proposal', 0.002),
                                          ('latex', 'n_\\mathrm{s}')])),
                            ('H0',
                             OrderedDict([('prior',
                                           OrderedDict([('min', 40),
                                                        ('max', 100)])),
                                          ('ref',
                                           OrderedDict([('dist', 'norm'),
                                                        ('loc', 70),
                                                        ('scale', 2)])),
                                          ('proposal', 2),
                                          ('latex', 'H_0')])),
                            ('omega_b',
                             OrderedDict([('prior',
                                           OrderedDict([('min', 0.005),
                                                        ('max', 0.1)])),
                                          ('ref',
                                           OrderedDict([('dist', 'norm'),
                                                        ('loc', 0.0221),
                                                        ('scale', 0.0001)])),
                                          ('proposal', 0.0001),
                                          ('latex', '\\Omega_\\mathrm{b} h^2')])),
                            ('omega_cdm',
                             OrderedDict([('prior',
                                           OrderedDict([('min', 0.001),
                                                        ('max', 0.99)])),
                                          ('ref',
                                           OrderedDict([('dist', 'norm'),
                                                        ('loc', 0.12),
                                                        ('scale', 0.001)])),
                                          ('proposal', 0.0005),
                                          ('latex', '\\Omega_\\mathrm{c} h^2')])),
                            ('Omega_m',
                             OrderedDict([('latex', '\\Omega_\\mathrm{m}')])),
                            ('omegamh2',
                             OrderedDict([('derived',
                                           'lambda Omega_m, H0: '
                                           'Omega_m*(H0/100)**2'),
                                          ('latex', '\\Omega_\\mathrm{m} h^2')])),
                            ('m_ncdm',
                             OrderedDict([('value', 0.06), ('renames', 'mnu')])),
                            ('Omega_Lambda',
                             OrderedDict([('latex', '\\Omega_\\Lambda')])),
                            ('YHe', OrderedDict([('latex', 'Y_\\mathrm{P}')])),
                            ('tau_reio',
                             OrderedDict([('prior',
                                           OrderedDict([('min', 0.01),
                                                        ('max', 0.8)])),
                                          ('ref',
                                           OrderedDict([('dist', 'norm'),
                                                        ('loc', 0.09),
                                                        ('scale', 0.01)])),
                                          ('proposal', 0.005),
                                          ('latex', '\\tau_\\mathrm{reio}')])),
                            ('z_reio',
                             OrderedDict([('latex', 'z_\\mathrm{re}')]))]),
     'sampler': {'mcmc': {'covmat': 'auto'}},
     'theory': OrderedDict([('classy',
                             OrderedDict([('extra_args',
                                           OrderedDict([('N_ncdm', 1),
                                                        ('N_ur', 2.0328)]))]))])}

    updated_info, products = cbyr.run(info)

**Comment by JesusTorrado** [comment]
Reproduced by myself. It looks that Class hard-codes some folders, so nothing I can do about it. I have added a note to the docs.
