### ISSUE TITLE
Error in H0 likelihood

### ISSUE THREAD

**Issue by jcolinhill** [CobayaSampler/cobaya#105]
There is a small error in the H0 likelihood in _H0_prototype.py, related to the normalization factor used in scipy.stats.norm.logpdf .  The error does not affect an MCMC run, as it is an additive constant to chi^2, but the chi^2 value output by Cobaya is not actually the correct chi^2.

Consider H0 = 72.19 km/s/Mpc.  The Riess2019 data give H0 = 74.03 \pm 1.42 km/s/Mpc.  The correct result is thus chi^2 = (74.03-72.19)^2/(1.42)^2 = 1.68.  However, the Cobaya output is chi^2 = 4.22.  It is easy to see how this happens:
>>> from scipy.stats import norm
>>> -2*norm.logpdf(72.19, loc=74.03, scale=1.42)
>>> 4.22

Looking at the scipy docs:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html

The problem is in the normalization factor, 1/sqrt(2pi scale^2).  This is entirely responsible for the discrepancy between the correct result and the Cobaya output for chi^2:
>>> -2 * np.log(1./np.sqrt(2.*np.pi*1.42**2.))
>>> 2.54
>>> 4.22-1.68
>>> 2.54

This problem does not affect chi^2 minimization since it is an additive constant to -2*log(L), but the actual chi^2 values output by Cobaya for the H0 likelihood are not correct.

**Comment by jcolinhill** [comment]
To be clear, the fix is very simple.  In _H0_prototype.py, just change
>>>return self.norm.logpdf(H0_theory) 
to
>>>return np.log(self.norm.pdf(H0_theory)*np.sqrt(2.*np.pi)*(self.H0_std))

(I suppose the sqrt(2*pi) could even be replaced with the pre-computed number to save a bit on computation.)

**Comment by misharash** [comment]
I think that the logpdf with 1/sqrt(2pi scale^2) normalization is fine, but then it's not quite right to calculate chi2 as -2*logpdf.

**Comment by misharash** [comment]
I wonder if this applies not only to H0, but to any normal distribution used.
I suspect that nuisance parameters priors may be shifting the chi2 relative to other codes as well.

**Comment by JesusTorrado** [comment]
Hi both,

I think the only likelihood using the normalised `scipy.stats.norm` is H0. I agree that it makes sense not to use it, since normalisation w.r.t. model parameters in a likelihood, which is a probability of the data instead, does not make much sense, and the chi2 normalisation at least has some meaning (Mahalanobis distance squared).

But that's not the case for priors, IMO. They should definitely be normalised, and it makes our life easier to make them so by default (e.g. when computing evidences).

**Comment by jcolinhill** [comment]
Hi Jesus, sure, I agree with your general points.  In this case the definition of chi^2 for this particular likelihood was just giving different answers than I expected (or than what is output by other codes for the SH0ES chi^2), so I wanted to figure out why and came across this minor issue.
Best,
Colin

**Comment by JesusTorrado** [comment]
Fixed in master. Thanks both for pointing it out and the comments!
