### ISSUE TITLE
incorrect brackets in check if "non linear" in classy's `extra_args`

### ISSUE THREAD

**Issue by lukashergt** [CobayaSampler/cobaya#106]
In line 298 of `cobaya/theories/classy/classy.py` it tests whether `"non linear"` is in `extra_args`:

```python
if (((any(("b" in cl.lower()) for cl in cls) and
      max(cls[cl] for cl in cls if "b" in cl.lower()) > 50) or
     any(("p" in cl.lower()) for cl in cls) and
     not self.extra_args.get("non linear"))):
    self.log.warning("Requesting BB for ell>50 or lensing Cl's: "
                     "using a non-linear code is recommended (and you are not "
                     "using any). To activate it, set "
                     "'non_linear: halofit|hmcode|...' in classy's 'extra_args'.")
```

The outer two brackets are doubled/redundant and the specific `not self.extra_args.get("non linear")` is **not paired with all other checks**, such that there are cases where the warning is incorrectly raised (granted, better this way then missing a needed warning, though).

Also, is the line 
```python
      max(cls[cl] for cl in cls if "b" in cl.lower()) > 50)
```
really testing for `'ell' > 50`? Naively I would have expected an `'ell'` keyword...

**Comment by JesusTorrado** [comment]
FIxed, thanks! I've also made the code more readable there.

About the double parenthesis, I sometimes use them in if's to force different tabbing with respect to the lines below (not very standard, I admit). Also, `cls` is a dict that contains Cl names as keys and their max ell's requested as values.
