### ISSUE TITLE
ERROR:classy:No Cl's were computed.

### ISSUE THREAD

**Issue by JavierOrjuela** [CobayaSampler/cobaya#107]
Hi guys,
I want to get the Cls from class code using the script showed in the  cobaya's doc:
"""""""""""""""""""""""""""""""""""""""""""'
fiducial_params = {
    'ombh2': 0.02629, 'omch2': 0.1479, 'H0': 67.85, 'tau': 0.0925,
    'As': 3.79e-9, 'ns': 0.9619 }
l_max = 1000
packages_path = ' '
info_fiducial = {
    'params': fiducial_params,
    'likelihood': {'one': None},
    'theory': {'classy': None},
    'packages_path': packages_path}
from cobaya.model import get_model
model_fiducial = get_model(info_fiducial)
model_fiducial.add_requirements({"Cl": {'pp': 0, 'bb': 0, 'ee': 2508, 'tt': 2508, 'eb': 0, 'te': 2508, 'tb': 0}})
model_fiducial.logposterior({})
Cls = model_fiducial.provider.get_Cl(ell_factor=False, units="muK2")
"""""""""""""""""""""""""""""""""""""""""""
Using "theory": camb I do not have any problem. But, for classy I get the following error:

[classy] *WARNING* Requesting BB for ell>50 or lensing Cl's: using a non-linear code is recommended (and you are not using any). To activate it, set 'non_linear: halofit|hmcode|...' in classy's 'extra_args'.
ERROR:classy:Serious error setting parameters or computing results. The parameters passed were {'ombh2': 0.02629, 'omch2': 0.1479, 'H0': 67.85, 'tau': 0.0925, 'As': 3.79e-09, 'ns': 0.9619} and {'output': 'pCl lCl tCl', 'lensing': 'yes', 'l_max_scalars': 2508}. See original CLASS's error traceback below.

[classy] *ERROR* Serious error setting parameters or computing results. The parameters passed were {'ombh2': 0.02629, 'omch2': 0.1479, 'H0': 67.85, 'tau': 0.0925, 'As': 3.79e-09, 'ns': 0.9619} and {'output': 'pCl lCl tCl', 'lensing': 'yes', 'l_max_scalars': 2508}. See original CLASS's error traceback below.

ERROR:classy:No Cl's were computed. Are you sure that you have requested them?
[classy] *ERROR* No Cl's were computed. Are you sure that you have requested them?

I used the automatic installation script for both theoretical codes. Any suggestion?
thanks.

**Comment by JesusTorrado** [comment]
Hi @JavierOrjuela 

Sorry for the (huge) delay! CLASS has produced an error in that case, as indicated ("ERROR Serious error[...]"). To see the cause of the error, you should set `debug: True` in the input, and then you'd see that: `CosmoSevereError('Class did not read input parameter(s): ombh2, omch2\n')`.

Since this is not immediately obvious, i have just added a commit suggesting to set `debug: True` if an error like this one is found.

Cheers!
