### ISSUE TITLE
Pass list parameters to CLASS 

### ISSUE THREAD

**Issue by tkarwal** [CobayaSampler/cobaya#110]
CLASS takes input for certain parameters as a list in its .ini files. Egs. include
m_ncdm = 0.04, 0.04, 0.04
scf_parameters = 10.0, 0.0, 0.0, 0.0, 100.0, 0.0
and many others. 

Without rewriting significant portions of CLASS, it would be nice to be able to pass these parameters through Cobaya to CLASS as well as have the option to vary them through an MCMC. By that I mean, be able to do something like: vary m_ncdm[0] and m_cdm[1] independently as separate MCMC parameters but fix m_ncdm[2]. 

One way of doing this, drawing form MontePython, is to define these parameters as 
m_ncdm__1
m_ncdm__2
m_ncdm__3 
in the cobaya .yaml file. I have added code to cobaya/theories/classy.py to read in all the parameters the sampler passes, and convert any with "__i"  to the correct format just before passing them on to CLASS. 
These then behave as independent parameters for the sampler, but CLASS reads them in correctly as 
m_ncdm = m_ncdm[0], m_ncdm[1], m_ncdm[2] 
where m_ncdm[i] are values and the above RHS is passed as a string. 

This is done by modifying the function 'calculate' in cobaya/theories/classy/classy.py to read (full function not printed here):

    def calculate(self, state, want_derived=True, **params_values_dict):
        # Set parameters
        ### new code to read in list parameters
        list_params = [key[:-3] for key in params_values_dict.keys() if '__1' in key.lower()]
        # this looks for any parameters defined as __1, i.e. the beginning of list params
        # and saves just the name minus the '__1' in a list
        if list_params:
            self.log.debug('Found params that have __1 in them:')
            self.log.debug(list_params)
        #else:
            #self.log.debug('Found no params that have __1 in them\n')
        # print statements to check that this works.
        for orig_name in list_params:
            list_param_values = [value for key,value in params_values_dict.items() if re.search(r'%s__([1-9])' % orig_name, key)]
            # Find the values of the others in the list parameter indices and stick them all together into one list of numbers
            values_str = ', '.join(['%g' % value for value in list_param_values])
            params_values_dict[orig_name] = values_str
            self.log.debug('Resetting list parameter %s = %s', orig_name, values_str)
            # Define a new input param with new name without the '__1' at the end as a string of comma-separated numbers
            for index in range(1, len(list_param_values)+1):
                del params_values_dict[orig_name + '__%i' % index]
                # Delete the entries for separate list params from input_params as we already account for the full list above
        ### END addition of new code
        self.set(params_values_dict)

I have checked that this works through the evaluate and the mcmc samplers. Feel free to run more checks. If you're satisfied, you could add this to Cobaya (sorry, I couldn't figure out how to submit a pull request). 

Cheers, 
Tanvi 

PS: also added 
`import re`
to the preamble of cobaya/theories/classy/classy.py .

**Comment by lukashergt** [comment]
Hi @tkarwal ,

I believe varying the masses independently is already implemented. Not sure whether this is exactly what you had in mind, but maybe this is what you are looking for to be put into your `.yaml` file:

```yaml
  m1:
    prior:
      min: 0
      max: 1
    drop: true
  m2:
    prior:
      min: 0
      max: 1
    drop: true
  m3:
    prior:
      min: 0
      max: 1
    drop: true
  m_ncdm:
    value: 'lambda m1, m2, m3: str(m1) + "," + str(m2) + "," + str(m3)'
    derived: false
```

**Comment by tkarwal** [comment]
Yes, this is what I had in mind, but didn't realise I could pass a parameter this way. Much more elegant a solution than mine, thank you!
