### ISSUE TITLE
cobaya-cosmo-generator missing pyside2

### ISSUE THREAD

**Issue by talabadi** [CobayaSampler/cobaya#114]
Hello,
I've installed cobaya following the instructions on the website without any errors, but when I reached the part of running cobaya-cosmo-generator I encountered the error of missing pyside2.
I tried the code for installing pyside2 and I found it is already installed, I tried removing it and reinstall, I tried update conda and conda packages but I still get the same error:
[cosmo_generator] *ERROR* PySide2 is not installed! Check Cobaya's documentation for the cosmo_generator ('Basic cosmology runs').

Here is the conda output:
$ conda install -c conda-forge pyside2
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
-------------------------------
Also,
$ python
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PySide2
>>> 

So I guess the problem is with cobaya's code...

**Comment by talabadi** [comment]
Solved:
for some reason `PySide2.QtWidgets` was not imported properly. After trying to modify _gui.py_ and fail I just added
`from PySide2.QtWidgets import QApplication`
to the _\__init\__.py_ file and it worked.

**Comment by JesusTorrado** [comment]
Hi @talabadi 

Sorry for the delay. I am unable to reproduce the issue. Any hint, please?

**Comment by talabadi** [comment]
I use Linux mint at the moment (I am not sure if it affects anything) with Anaconda.

When I tried to run cobaya-cosmo-generator I received an error message saying that PySide2 was missing even thought I was able to import it:
[cosmo_generator] *ERROR* PySide2 is not installed! Check Cobaya's documentation for the cosmo_generator ('Basic cosmology runs').

I followed the origin of the error to _gui.py_ in the _cosmo_input_ folder where I found the import call for the PySide2 package. For some reason it did not work. So I tried to import the package at an earlier stage: from the __init__.py file in this folder, and it solved the problem.

**Comment by JesusTorrado** [comment]
Hi @talabadi,

I can finally reproduce it, after updating to Ubuntu 20.04. It's very very weird, since the import order shouldn't matter so much. Looking for an alternative solution that is more resilient to pySide2 not being installed.

**Comment by JesusTorrado** [comment]
Should be solved. The weird dependence of the error on import order came from `matplotlub.pyplot`, so substituting it for `matplolib.cm` fixes it.
