### ISSUE TITLE
skip_global parameter in install file

### ISSUE THREAD

**Issue by xgarrido** [CobayaSampler/cobaya#123]
I am wondering if this line https://github.com/CobayaSampler/cobaya/blob/master/cobaya/install.py#L123 should be not be replaced by something like

```python
if kwargs.get("skip_global"):
```
otherwise I'm getting error like

```
  File "/tmp/mflike/pyenv/lib/python3.8/site-packages/cobaya/install.py", line 138, in install
    if kwargs["skip_global"]:
KeyError: 'skip_global'
```

(for instance, the error is raised within the unit test of https://github.com/simonsobs/LAT_MFLike/blob/master/mflike/tests/test_mflike.py)

**Comment by JesusTorrado** [comment]
Fixed in master, thanks!
