### ISSUE TITLE
Restarting MCMC with multiple processes

### ISSUE THREAD

**Issue by misharash** [CobayaSampler/cobaya#124]
I was trying to resume a 4 chains MCMC run with 4 processes (which should be okay) and got the following error:
```
  File "/usr/lib/python3.8/site-packages/cobaya/samplers/mcmc/mcmc.py", line 105, in initialize
    "was %d and now is %d.", max(self.mpi_size, 1),
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```
As far as I understood, self.mpi_size keeps its default value of None (I haven't found any piece of code setting another value) so the previous number of chains is assumed to be 1 (which is not true). Therefore it is assumed that I'm trying to resume with a changed number of chains, rises error and gets another error in process.
If I disable this chain number check, the resume operation succeeds.

**Comment by cmbant** [comment]
self.mpi_size is None? If so could try "self.mpi_size or 0", though probably wouldn't help with original issue.

**Comment by misharash** [comment]
Yes, if I just change to "self.mpi_size or 0", I get an error that I'm trying to resume with different number of chains (which is not the case actually).
To my understanding, self.mpi_size should contain the previous run's number of chains, which I guess can be obtained by counting the chain output files (prefix.%d.txt) somewhere above in the code.

**Comment by cmbant** [comment]
I think write_checkpoint should put mpi_size in the checkpoint .yaml - is it not there?

**Comment by JesusTorrado** [comment]
I am taking a look at it right now. Maybe I broke it when I re-wrote a while ago how the checkpoint file was written. It sucks not to have MPI tests in pytest.

**Comment by misharash** [comment]
The checkpoint files contain mpi_size. I guess the problem then was caused by running minimization that deleted the checkpoint (and also progress file). Why would it do this?

**Comment by JesusTorrado** [comment]
I see. Every time a new sampler is called, some cleanup is done. I guess the minimiser is a special case and it shouldn't do that. Checking...

**Comment by JesusTorrado** [comment]
This was a tricky one. Fixed. Please let us know if you can still reproduce it!
