### ISSUE TITLE
Cosmology post-processing failure

### ISSUE THREAD

**Issue by misharash** [CobayaSampler/cobaya#125]
When I tried to run post-processing (adding BAO likelihoods) on Planck18 + several local H0 measurements run, I got the following error:
`[collection] *ERROR* Got 18 values for the derived parameters. Should be 16.`
It seems like the missing derived parameters are chi2's.

**Comment by JesusTorrado** [comment]
Hi @misharash 

Can you send me the `.updated.yaml` file of the original chain, a fraction of the original chain, and the post-processing yaml via email, so that I can reproduce it? (My email should be super easy to find)

**Comment by misharash** [comment]
Hi @JesusTorrado 
I sent the files to you yesterday, but am not sure if they weren't lost. Anyway, I've found even more minimalistic example to reproduce the error:
[planckH3LCDM.zip](https://github.com/CobayaSampler/cobaya/files/5649021/planckH3LCDM.zip)
Thanks.

**Comment by cmbant** [comment]
I think this should now be fixed by https://github.com/CobayaSampler/cobaya/pull/160, but I can't easily test this specific case as classy doesn't run on my devel machine - great if someone else can try it.

**Comment by misharash** [comment]
Thanks, with #160 it works indeed.
