### ISSUE TITLE
Multiple bao.generic likelihoods

### ISSUE THREAD

**Issue by Pablo-Lemos** [CobayaSampler/cobaya#126]
Hello,

I am trying to use bao.generic with multiple BAO files. My first approach was to use in my ini file: 

likelihood:
  bao.generic: 
    measurements_file: bao_file_1
    cov_file: cov_file_1
  bao.generic: 
    measurements_file: bao_file_2
    cov_file: cov_file_2

However, cobaya only uses the second file and covariance. Is there a way to make it use both?

Thanks!

**Comment by cmbant** [comment]
Not sure there's an easy way round that other than making a trivial derived class with a new name. (or combining both sets of data into one).

**Comment by JesusTorrado** [comment]
Implemented in #135
