### ISSUE TITLE
Cocoa - Cobaya for DES-Y3 - and Thanks

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#129]
Hi @JesusTorrado and @cmbant,

First, I would like to thank you two a lot for all the support you have given me over the years. I would like to say that we are making good progress in integrating the cobaya framework in one of the two official DES pipelines. 

The backbone of the code is already public (although there is a lot of code comparison with ComoSiS I will have to perform in the next few weeks) - https://github.com/CosmoLike/cocoa - and I want to make sure I cite Cobaya enough in the readme file. 

Because we had to control a lot of the environment we are using - we copied all required code (even pip packages such as numpy and scipy!) into our repo. We make sure to say everywhere in the README how much our work is derived from yours. Even the name Cocoa derives from Cobaya-Cosmolike framework :)

I used a lot more bash scripts than python to make all the integration, but I am pretty sure you two could have done the integration much better and faster using nice python scripts :). I apologize for my ignorance on that. 

Cosmolike can make your future implementation of DES-Y3 in Cobaya, when the data becomes public, way simpler - as you will have code to compare. (pretty sure you are going to create a crazy fast super nice python only likelihood :) ). Cosmolike is way - way faster than ComoSiS - running DES-Y3 pipeline in 1 second (4 openMP cores) + camb time. But I am sure you will create something that runs around 10^-2 seconds or less :p 

The available code still has not included our complete interface to Cobaya for DES-Y3 - but we will in the future.

Repo has code in v0.9 - pre-release (there is nothing confidential there about DES-Y3 - don't worry :p) - and I just want to make sure you two are ok with our citations to your work on our readme. If not - what can I change?

**Comment by cmbant** [comment]
Can you not include a specific cobaya commit you need as a git submodule, rather than copying all the files?

**Comment by vivianmiranda** [comment]
We tried git submodules and the students were very confused. We can fairly easily just make a git clone script. of the cobaya folder (tied to a specific commit). Does that sound good?

**Comment by vivianmiranda** [comment]
Same for CAMB...we fork it (so we can mod it) then do a git clone script?

**Comment by JesusTorrado** [comment]
Hi @vivianmiranda 

We are very happy that Cobaya is being used in DES, be it the main pipeline or not, and very grateful to you for doing all the work involved! The acknowledgements look fine to me.

Ideally, in the future Cobaya itself would contain as little cosmological code as possible, by means of importing the official likelihoods (including a Cobaya interface) from their own repo, which would be maintained by the corresponding collaboration. In this case, whenever Y3 is released, I'd propose putting the Cocoa bare likelihood in its own repo (following [this](https://cobaya.readthedocs.io/en/latest/cosmo_external_likelihood_class.html)) and then we can help you make it faster if needed.

As for the other Cobaya modifications, at some point I'd be interested in doing a serious comparison between Minuit, PyBOBYQA and whatever scipy algorithm. As for MultiNest, I must say that my experience writing an interface for MontePython has not been very good: the Python interface needed quite a bit of work (at least a while ago! not sure about now), and it was impossible to propagate likelihood exceptions through it (it would just segfault when the likelihood failed). Are you sure that PolyChord does not do the same work equally well? (Also, there appears to be a development of PolyChord in the works that will make it blazing fast).

As soon Y3 is out, let's get to work!

**Comment by vivianmiranda** [comment]
Hi Jesus - yes I've shown that for DES-Y3 - Polychord is way better than Multinest (appendix of https://arxiv.org/abs/2009.14241) - with very detailed comparison. But in a collaboration, it is not easy to make people switch code and Multinest is still widely used (together with emcee). So in long term to better compare results with CosmoSiS it can be advantageous to at least have an emcee (there is a new version of emcee out this week on arxiv!). Also people sometimes wants results fast even if take way more cpu-hours and for that emcee is great.

**Comment by vivianmiranda** [comment]
and yes as soon is DES is out (also DES extensions which will make it sometime - there are two extensions project now - there are some deadlines for the data release I think) - we should work on the Cosmolike likelihood as a standalone code. :)
