### ISSUE TITLE
Resuming a non-reproducible chain

### ISSUE THREAD

**Issue by joezuntz** [CobayaSampler/cobaya#13]
It looks like it isn't possible to resume a chain that has external priors and likelihoods.

Is there a way around this?  I have a run which I know is reproducible (because I can check externally) but because of the need to include dynamically generated information in a closure I need to use external functions.

If there isn't then an option to skip the check when resuming would be handy.

**Comment by JesusTorrado** [comment]
Hi Joe,

I'll take a look at it next week. In the meantime, if you are sure that your input is the same, and just as a workaround, you can comment out the `raise` in line 121 of `cobaya/output.py`.

Have a nice weekend!
Jesús

**Comment by JesusTorrado** [comment]
Fixed in 4b148b5 (v1.1.1). Now it ignores non-serializable Python objects when resuming.

Some complex cases may still fail. Let me know if that's the case, please. Closing for now.
