### ISSUE TITLE
sigma_8 for BAO

### ISSUE THREAD

**Issue by Pablo-Lemos** [CobayaSampler/cobaya#130]
Is there an easy way to make sure that z=0 is in the redshifts array? If so, I think it would be good to make that the default option. Otherwise, one could naively install the code, run it for BAO, and think they got a low sigma_8

_Originally posted by @Pablo-Lemos in https://github.com/CobayaSampler/cobaya/issues/128#issuecomment-731122909_

**Comment by cmbant** [comment]
Let's try to consolidate in https://github.com/CobayaSampler/cobaya/pull/133. Let me know if it works for you.
