### ISSUE TITLE
bug on _extract_params - CAMB.py

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#136]
Hello Jesus,

Happy new year!

There is a bug in the function below
 
   ```
def _extract_params(self, set_func):
        args = {}
        params = []
        pars = getfullargspec(set_func)
        for arg, v in zip(pars.args[1:], pars.defaults[1:]):
            print(arg, v)
            if arg in self.extra_args:
                args[arg] = self.extra_args.pop(arg)
            elif isinstance(v, numbers.Number) or v is None:
                params.append(arg)
        return args, params
```

The line 

` for arg, v in zip(pars.args[1:], pars.defaults[1:]):`

should be replaced by

` for arg, v in zip(pars.args[1:], pars.defaults[0:]):`

otherwise, the last param is not read and not considered part of CAMB for Cobaya.

Be safe!
Best Regards
Vivian Miranda

**Comment by cmbant** [comment]
It looks as though I may have fixed this in CAMB (https://github.com/cmbant/CAMB/blob/4e22fdd57dc4ba7a48a5609d2297d55efbfec5b1/camb/camb.py#L196)  but overlooked the case of the non-linear P_k arguments - I think that's the only case where there's an issue?

**Comment by vivianmiranda** [comment]
I think so too

**Comment by vivianmiranda** [comment]
Well - to be fair - the piece of code I extracted is from Cobaya/theory/CAMB.py

**Comment by cmbant** [comment]
Try https://github.com/CobayaSampler/cobaya/commit/d757003063303a616317c47e4c8179864a4f96f8 ? (just copied across tested camb code without re-testing in cobaya)

**Comment by cmbant** [comment]
I've now merged to master, let me know if any further issue with this
