### ISSUE TITLE
TRanges_Add_delta: end must be larger than start

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#137]
Hello again,

When running w0-wa, I am getting a lot these types of errors on CAMB

` 
TRanges_Add_delta: end must be larger than start
ERROR STOP 
`

even when `stop_at_error: False`.

Any tips on how to circumvent that?

Best
Vivian

**Comment by cmbant** [comment]
This doesn't look familiar, do you know the CAMB parameters?

**Comment by vivianmiranda** [comment]
The camb params I used on my yaml file?

**Comment by cmbant** [comment]
Preferably a dump of the CAMB parameters being used by CAMB when you get the error

**Comment by vivianmiranda** [comment]
Thanks

How do I do that - the errors happens stochastically on a chain.

Best

On Jan 11, 2021, at 7:20 AM, Antony Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


Preferably a dump of the CAMB parameters being used by CAMB when you get the error

**Comment by cmbant** [comment]
You could print the camb params object at each call for the purpose of debugging

**Comment by vivianmiranda** [comment]
Thanks

This is a cosmology that breaks CAMB

  As_1e9 = 2.1
   ns = 0.96605
   H0 = 59.1064
   omegab = 0.0553237
   omegam = 0.329646
   w = -0.612116
   wa = 0.942957
mnu = 0.06
tau = 0.0543

Best
Vivian

On Jan 11, 2021, at 9:35 AM, Antony Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


External Email


You could print the camb params object at each call for the purpose of debugging

**Comment by vivianmiranda** [comment]
Hi Lewis,

The line that is failing is the following (on CMBmain.f90)

`call Evolve_q%Add_delta(q_switch, min(q_cmb,qmax), dkn2)`

after the line `if (qmax > q_switch) then`

with 

q_switch = 1.4674951901017399
q_cmb = 0.67049975741897860
qmax = 1.9240427821588082

Best
Vivian

**Comment by cmbant** [comment]
Thanks. I guess your theta* is rather crazy, so the L-k mapping is quite far off expectations. Try adding something like
q_cmb = max(q_switch*2, q_cmb)
after
https://github.com/cmbant/CAMB/blob/05f97477be48fa15e9dbf552fe66a3351d61543b/fortran/cmbmain.f90#L876 ?

**Comment by cmbant** [comment]
The more fundamental reason is that for these parameters w becomes larger than zero, so the dark energy dynamics becomes important in the early universe. It's this change in pre-recombination that's actually messing it up. Maybe should add a prior/error message for w+wa > 0?

**Comment by vivianmiranda** [comment]
Thanks Lewis,

Yesterday I added such prior. But it would be interesting that CAMB fails w/ stopping the chain given that stop_on_error flag was set to false.

My flag was more towards this point - CAMB failing without stopping the chain - than about thinking w0+wa>0 is viable.

Best
vivian

On Jan 13, 2021, at 3:17 AM, Antony Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


External Email


The more fundamental reason is that for these parameters w becomes larger than zero, so the dark energy dynamics becomes important in the early universe. It's this change in pre-recombination that's actually messing it up. Maybe should add a prior/error message for w+wa > 0?

**Comment by cmbant** [comment]
Yeah, the code does actually work fine for some cases with w+wa>0, but I agree usually this will be unintentional so I've added a general error for this case to catch it earlier. See https://github.com/cmbant/CAMB/commit/1d81358cbf3a9861c153b873775ad27ea69bb11a

**Comment by vivianmiranda** [comment]
thanks lewis - you are the best! :)

On Jan 13, 2021, at 8:38 AM, Antony Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


External Email


Closed #137<https://github.com/CobayaSampler/cobaya/issues/137>.
