### ISSUE TITLE
Runs compatibility check prevents resuming with custom likelihood and python_path

### ISSUE THREAD

**Issue by misharash** [CobayaSampler/cobaya#139]
Hello.
With cobaya 3.0.2 (but with 3.0.3 happens exactly the same) I tried to resume a run with custom likelihoods located in separate files. I am sure nothing has changed at all, though I got the following: `[output_mpi] *ERROR* Old and new run information not compatible! Resuming not possible!`
When I turned on debug, it said where the difference was: `[input] {} (old) vs {'python_path': '.'} (new)`, despite the fact the python_path was actually identical, I used the same unchanged YAML config.
It seems to me that `python_path` option is somehow not loaded to the old run info for this comparison. I'll try to make a toy reproduction to check this and send it here a bit later.

**Comment by misharash** [comment]
I also think it may be convenient to have a built-in option to skip compatibility check.

**Comment by misharash** [comment]
So this is the minimal example I thought of that reproduces the issue: 
[python_path_issue.zip](https://github.com/CobayaSampler/cobaya/files/5897987/python_path_issue.zip)
After running (`cobaya-run test.yaml` in the directory where the archive is unpacked) the run can't be resumed (`cobaya-run -rd test.yaml`) for exactly the same reason.

**Comment by cmbant** [comment]
Please try https://github.com/CobayaSampler/cobaya/pull/152 which has some fixes for this and https://github.com/CobayaSampler/cobaya/issues/153

**Comment by misharash** [comment]
Thanks, look forward to the merging of #152 and next release version.
In January I temporarily overcame this by removing `python_path` options from yaml configs and moving the external code to common python path (as I've described in #153).
Then I had put symlink to external code directory to common python path and was able to use it in Cobaya as `dirname.filename.classname`. I think mentioning such possibility in external theory/likelihoods guidelines in the docs might be helpful.
