### ISSUE TITLE
Small bug in Planck Likelihood

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#14]
This is a bug that I have solved myself for some time - and I forget to tell you. See the picture below - without this fixed I was unable to path with an external Planck Likelihood

<img width="763" alt="screen shot 2018-12-07 at 4 52 26 pm" src="https://user-images.githubusercontent.com/3210728/49678282-920d5b80-fa40-11e8-98e8-1e63630e5549.png">

**Comment by JesusTorrado** [comment]
Thanks! Just to clarify: you mean an external Planck likelihood code or what they call "clik files"?

**Comment by vivianmiranda** [comment]
On Dec 14, 2018, at 10:37 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Just to clarify: you mean an external Planck likelihood code or what they call "clik files”?

Yes - external

**Comment by JesusTorrado** [comment]
Yup, but external "click files" OR clik code OR both?

**Comment by vivianmiranda** [comment]
Both

Best

Vivian Miranda

On Dec 14, 2018, at 10:38 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Just to clarify: you mean an external Planck likelihood code or what they call "clik files"?

**Comment by JesusTorrado** [comment]
Should be fixed in 1.1, thanks!
