### ISSUE TITLE
CMB ignores H0 input if run with Hubble constant likelihoods

### ISSUE THREAD

**Issue by misharash** [CobayaSampler/cobaya#141]
Hello. With cobaya 3.0.3 I started running with CLASS and Planck18+H0 measurements, using `H0` instead of `theta_s` as input parameter. I've noticed that H0 gets into a very fast parameter block, which doesn't make sense - Boltzmann code output depends on H0 non-trivially, and CLASS is the bottleneck of performance in my run. The output confirmed my concern that power spectra aren't actually recomputed when changing H0, and the data seemed to respect only H0 measurement.
Here are the example configs to reproduce: [planckH0.zip](https://github.com/CobayaSampler/cobaya/files/5971840/planckH0.zip)

**Comment by misharash** [comment]
Specifying `H0` requirement to `classy` explicitly (e.g. [planckH0-nested-corrected.yaml](https://github.com/CobayaSampler/cobaya/files/5971875/planckH0-nested-corrected.yaml.txt)) seems like a workaround - then H0 gets in a slow block separate from others, which makes sense - H0 likelihood is to be recomputed only for it and not for other params.

**Comment by cmbant** [comment]
I think this should be fixed by https://github.com/CobayaSampler/cobaya/pull/152

**Comment by misharash** [comment]
That is true, thank you. I installed #152 and my original configs seems to work as expected, H0 gets into a slow block.
Interestingly, the workaround config I used then fails now saying `*ERROR* Could not find anything to use input parameter(s) {'A_s', 'omega_cdm', 'tau_reio', 'omega_b', 'n_s'}.`
If I list all CLASS input parameters explicitly, it works.

**Comment by cmbant** [comment]
That's true. Not very clear what the best behaviour should be, but I've tweaked it (https://github.com/CobayaSampler/cobaya/pull/152/commits/68afda4588f14907134913e8544c74406cf2c9c4) so it should now work more like before in allowing both requires and agnostic parameters. (ultimately hope to get rid of agnostic components altogether)

**Comment by misharash** [comment]
Great, now it all works. Thanks a lot.
