### ISSUE TITLE
Better Hubble likelihoods

### ISSUE THREAD

**Issue by cmbant** [CobayaSampler/cobaya#151]
It's been on the list of things for some time, but was reminded by https://arxiv.org/abs/2103.08723: it would be nice to make "HST"-like H0 likelihoods that actually constrain what the data constrains rather than naive Gaussian priors on H0. At the simplest level perhaps it could be done by just making the magnitude in the Pantheon likelihood an input parameter that could be constrained by local calibrator "h0"- likelihood. (Maybe @Pablo-Lemos has something along these lines already?)

**Comment by Pablo-Lemos** [comment]
I actually do, but in CosmoMC. Will rewrite it for cobaya on Monday
