### ISSUE TITLE
Easier way to run

### ISSUE THREAD

**Issue by cmbant** [CobayaSampler/cobaya#156]
We've discussed this a bit before, but it continues to annoy me there's no easy way to reproduce things like "cobaya-run -r script.yaml" from a script, without loading and  modifying the yaml.

Any objections to splitting run_script into a part using argparse, then pass the result to a general separate run function that can also be called programmatically with filename and options? 

I would probably opt for just modifying the run() function to do this, where the first argument is either  a dictionary (as now) or a file name, and then the optional parameters to change things like resume, force etc  - but I recall there was some reason @JesusTorrado wasn't keen on that (?).

**Comment by JesusTorrado** [comment]
Happy to rethink it, but please let me catch up with the rest in the following ~1week or so.

**Comment by cmbant** [comment]
Straw implementation in https://github.com/CobayaSampler/cobaya/pull/158 (no rush..)
