### ISSUE TITLE
Getting derived parameters from external likelihood class

### ISSUE THREAD

**Issue by seshnadathur** [CobayaSampler/cobaya#168]
Hi,

I've written my own external likelihood class (following the outlines [here](https://cobaya.readthedocs.io/en/latest/cosmo_external_likelihood_class.html)) and this works fine. But now I want to modify the `logp` method of this class to also return some derived parameters it calculates. It's not clear to me how to get this to work.

The documentation for getting derived parameters from external likelihood functions [here](https://cobaya.readthedocs.io/en/latest/example_advanced.html#example-advanced-likderived) and [here](https://cobaya.readthedocs.io/en/latest/likelihoods.html#external-likelihood-functions) is fine, but it is not clear from the documentation how to extrapolate these instructions to work with an external likelihood class. I tried a few permutations of the input yaml but all the ones I tried either gave a yaml parsing error or did not like the `logp` method returning a derived parameter dict in addition to the log likelihood.

Is it possible to do this, and if it is, could you add a description to the documentation please? Thanks!

**Comment by cmbant** [comment]
In logp you can use the special "_derived={}" input parameter, and set values in the passed-in dictionary.

Instead of using logp, you can also just implement "calculate" and set both state["logp"] and state["derived"]. (by default Likelihood's calculate just calls logp, setting derived from _derived).

There is some doc in https://cobaya.readthedocs.io/en/latest/theories_and_dependencies.html (Likelihood is just a subclass of Theory).

**Comment by seshnadathur** [comment]
Thanks, this worked! 

In case anyone else reads this, in order to then get the derived parameter output to chains, one also needs to add `derived_parameter_name` to the `MyLikelihood.yaml` file for the class and explicitly add `derived: True`. (Maybe that's obvious, but it took me some time to figure it out.)

It might be good to add a mention to the docs in [https://cobaya.readthedocs.io/en/latest/cosmo_external_likelihood_class.html](https://cobaya.readthedocs.io/en/latest/cosmo_external_likelihood_class.html)?

**Comment by cmbant** [comment]
Sure, I added something at https://github.com/CobayaSampler/cobaya/blob/info_dicts/docs/cosmo_external_likelihood_class.rst (pending merge)

**Comment by cmbant** [comment]
Now merged to master
https://cobaya.readthedocs.io/en/latest/cosmo_external_likelihood_class.html
