### ISSUE TITLE
Disable burn in for nested sampling chains

### ISSUE THREAD

**Issue by williamjameshandley** [CobayaSampler/cobaya#17]
Burn in has no meaning for nested sampling. Ideally it should be disabled or throw an exception if users try to use it in the case of analysing nested sampling chains. This was the root cause of this issue:

https://github.com/PolyChord/PolyChordLite/issues/6#issuecomment-446764417

This was raised in the [GetDist repo](https://github.com/cmbant/getdist/issues/27), but is likely better addressed by a modification to Cobaya

**Comment by JesusTorrado** [comment]
Probably will fix in cmbant/GetDist#27
