### ISSUE TITLE
`mpi4py` should probably be made a hard dependency

### ISSUE THREAD

**Issue by appetrosyan** [CobayaSampler/cobaya#176]
When submitting a job on an HPC, it may happen that the `mpirun`  does not establish a communication channel between the processes. Not only does that not terminate the job batch (wasting the HPC-hours), it produces an error buried deep in the middle of the job's output. 

@williamjameshandley found that installing `mpi4py` fixes the issue for the CSD3 cluster. 

As an easy workaround, it may be useful to just make `mpi4py` a hard dependency of `cobaya` in `setup.py`.

**Comment by JesusTorrado** [comment]
Hi @appetrosyan 

We are working on an update that should take care of this issue. I will check with you again when it's ready to see if it solves your particular case.

**Comment by cmbant** [comment]
Please check current master - this should give an error if you accidentally start multiple processes not with MPI. (making mpi4py a hard dependency likely causes problems in cases where head nodes on clusters do not allow mpi)

**Comment by appetrosyan** [comment]
Dear @cmbant , 

> Please check current master - this should give an error if you accidentally start multiple processes not with MPI

Works. This fixes the original issue.
