### ISSUE TITLE
cobaya-cosmo-generator and getdist-gui installation issues?

### ISSUE THREAD

**Issue by kuijken** [CobayaSampler/cobaya#178]
I have finally installed cobaya on my mac, following the instructions on the site. I have v3.0.4 . MacOS10.15.7. Installation worked fine.
I am getting error messages from cobaya-cosmo-generator and from getdist-gui as follows. PySide2 is installed... Any ideas?
I repeated the installation on my linux machine and get the same issue with cobaya-cosmo-generator there as well.
Apologies if the solution is trivial...

? cobaya-cosmo-generator
Traceback (most recent call last):
  File "/Users/kuijken/.local/bin/cobaya-cosmo-generator", line 5, in <module>
    from cobaya.cosmo_input import gui_script
ImportError: cannot import name 'gui_script' from 'cobaya.cosmo_input' (/Users/kuijken/.local/lib/python3.7/site-packages/cobaya/cosmo_input/__init__.py)
           
?getdist-gui
GetDist GUI.app not found; not running getdist-gui, getdist package not installed or no valid PySide2 found when setup was run. Running script...

this gives me a window with some limited functionality, I can make triangle plots but the menu items in the task bar do not work.

**Comment by cmbant** [comment]
Try running in a clean conda environment, e.g.

`conda create -n py39forge -c conda-forge python=3.9 scipy pandas matplotlib PySide2`

**Comment by cmbant** [comment]
(how did you install PySide2? It doesn't work for me via pip)

**Comment by kuijken** [comment]
I am not using conda, and PySide2 installs fine for me with pip; it certainly is there (v5.15.2) . Still puzzled.
[And my linux machine and mac give exactly the same error for cobaya-cosmo-generator .]

The cobaya-run example with gaussian.yaml runs just fine FWIW...

**Comment by JesusTorrado** [comment]
Hi @kuijken 

For the linux case, is that above the full traceback? nothing else?

Also in linux, could you please tell us the output of

    python -c "from PySide2.QtWidgets import QWidget"

making sure that `python` is exactly the same python with which you ran `pip`?

**Comment by kuijken** [comment]
Hi Jesús,
That is the entire traceback, yes:
                                                                                                                                                                                                                                                                                                                                                                             > cobaya-cosmo-generator 
Traceback (most recent call last):
  File "/home/kuijken/.local/bin/cobaya-cosmo-generator", line 5, in <module>
    from cobaya.cosmo_input import gui_script
ImportError: cannot import name 'gui_script' from 'cobaya.cosmo_input' (/home/kuijken/.local/lib/python3.9/site-packages/cobaya/cosmo_input/__init__.py)
 
and the output of python -c "from PySide2.QtWidgets import QWidget" is null.

I made sure it's the same python all the way through.



> On 20 May 2021, at 14:57, Jesús Torrado ***@***.***> wrote:
> 
> 
> Hi @kuijken
> 
> For the linux case, is that above the full traceback? nothing else?
> 
> Also in linux, could you please tell us the output of
> 
> python -c "from PySide2.QtWidgets import QWidget"
> 
> making sure that python is exactly the same python with which you ran pip?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

**Comment by cmbant** [comment]
Pyside2 install OK for me with pip too, but I can't get it to actually work (on Windows though). Making a clean conda environment (currently pyside 5.13) seems to work reliably on all systems I've tried.

**Comment by JesusTorrado** [comment]
I am dumbfounded. While I think of something else, could I ask you to try in linux (single-line command)

    $(echo $(head -n 1 $(which cobaya-run)) | cut --complement -c1-2) -c "from PySide2.QtWidgets import QWidget"

and check that it does not produce an error?

Also, did you install cobaya with `pip` or from git master?

**Comment by kuijken** [comment]
That does not produce an error... I can just go into python and import PySide2

and I installed cobaya with pip, yes, following the readthedocs instructions.

I tried with a clean conda environment as Anthony suggested but no joy...

conda create -n cobayaenv -c conda-forge python=3.9 scipy pandas matplotlib PySide2

conda activate cobayaenv

python -m pip install cobaya

which cobaya-cosmo-generator
/Users/kuijken/opt/anaconda3/envs/cobayaenv/bin/cobaya-cosmo-generator

cobaya-cosmo-generator
Traceback (most recent call last):
  File "/Users/kuijken/opt/anaconda3/envs/cobayaenv/bin/cobaya-cosmo-generator", line 5, in <module>
    from cobaya.cosmo_input import gui_script
ImportError: cannot import name 'gui_script' from 'cobaya.cosmo_input' (/Users/kuijken/opt/anaconda3/envs/cobayaenv/lib/python3.9/site-packages/cobaya/cosmo_input/__init__.py)

Same goes for an installation based on python3.9 .

I'm pretty sure PySide2 is installed correctly - I copied the examples tetrix.py from the pyside-setup github repo and
managed to play tetrix just fine!

**Comment by cmbant** [comment]
Does the latest getdist master work OK in the conda env? I tried it yesterday on a Mac and it seemed to work (though you may need to set your Mac developer app permissions etc).
```
pip uninstall getdist
git clone git@github.com:cmbant/getdist.git
pip install getdist
getdist-gui
```

**Comment by kuijken** [comment]
victory! I tried this and getdist now works. This did not fix cobaya-cosmo-generator yet though. 
Many thanks.

**Comment by cmbant** [comment]
Phew! Try similar git install of latest cobaya master?

**Comment by kuijken** [comment]
Alas that last suggestion (git installing cobaya master) did not fix the cosmo-generator scipt. But I now have cobaya installed and working (but not the cobaya-cosmo-generator script), as well as getdist-gui. Good enough to move on. Thanks again for the unblocking.

**Comment by JesusTorrado** [comment]
Sorry not to have been able to help! I'd be happy to follow up, but honestly, I have no clue of what may be causing it!

**Comment by cmbant** [comment]
Looking at the differences between getdist and cobaya gui initialisation:
getdist has 
`os.environ['QT_API'] = 'pyside2'`

- might be worth a try?

(plus in Mac getdist makes a mac .app wrapper, but getdist does run - partially- without it)
