### ISSUE TITLE
interdependency between theory Classes

### ISSUE THREAD

**Issue by zhaoruiyang98** [CobayaSampler/cobaya#183]
Hi,
I'm trying to implement a new theory Class which depends on some CAMB outputs.
I read [this](https://cobaya.readthedocs.io/en/latest/theories_and_dependencies.html) part of documentation but get quite confused about the example.

I have the following questions (I don't quite understand how cobaya handle interdependency between theorys, so my question itself may be ambiguous, I feel sorry for that):
1. What's the difference between `get_requirements` and `must_provide`?
Does this mean `must_provide` can return conditional requirements based on input and it can also receive "settings" (e.g. `kmax`)？
2. I implemented the example but when I ran it, I got an error "Component 'example.BCaculator' seems not to depend on any parameters (neither directly nor indirectly)". My implementation looks like this:
```python
from cobaya.theory import Theory
from cobaya.likelihood import Likelihood

class ACalculator(Theory):
    def get_requirements(self):
        return {'b_derived': None}
    
    def must_provide(self, **requirements):
        if 'A' in requirements:
            return {'B': {'kmax': requirements['A'].get('kmax', 10)}}
    
    def get_can_provide(self):
        return ['A']
    
    def get_can_provide_params(self):
        return ['Aderived']
    
    def calculate(self, state, want_derived, **params_values_dict):
        state['A'] = self.provider.get_result('B') * self.provider.get_params('b_derived')
        state['derived'] = {'Aderived': 10}

class BCalculator(Theory):
    def initialize(self):
        self.kmax = 0
    
    def get_can_provide_params(self):
        return ['b_derived']
    
    def get_can_provide(self):
        return ['B']
    
    def must_provide(self, **requirements):
        if 'B' in requirements:
            self.kmax = requirements['B'].get('kmax', 10)
    
    def calculate(self, state, want_derived, **params_values_dict):
        if self.kmax:
            state['B'] = 10 * self.kmax
        
        if want_derived:
            state['derived'] = {'b_derived': 10}


class JustTest(Likelihood):
    def get_requirements(self):
        return {'A': {'kmax': 10}, 'theta': None, 'sigma': None}

    def logp(self, **params_values):
        theta, sigma = params_values['theta'], params_values['sigma']
        A = self.provider.get_result('A')
        chi2 = (theta - A)**2 / sigma**2
        print(f"theta={theta:.3f}, A={A:.3f}")
        return -0.5 * chi2
```
and my YAML file:
```yaml
theory:
  example.ACalculator:
    python_path: .
  example.BCalculator:
    python_path: .

likelihood:
  example.JustTest:
    python_path: .

params:
  theta: 1000
  sigma: 0.1

sampler:
  evaluate:

output: chains/example
```
3. I also don't understand the role of `kmax`. It seems like `kmax` is not a (fixed/sampled/derived) parameter, it's an option/setting instead. I wonder is it possible for `ACalculator` to pass parameters to `BCalculator` with `{'A': {'kmax': 10}}`-like structure?
4. Let's consider this case: theory A depends on theory B, theory C also depends on theory B but needs a different setting, will they conflict?
I write the following piece of code:
```python
from cobaya.theory import Theory

class A(Theory):
    def must_provide(self, **requirements):
        if 'a' in requirements:
            return {'b': {'setting': 2}}
    
    def calculate(self, state, want_derived, **params_values_dict):
        state['a'] = self.provider.get_result('b')
    
    def get_can_provide(self):
        return ['a']

class B(Theory):
    def initialize(self):
        self.setting = 0

    def get_requirements(self):
        return ['b_param']

    def must_provide(self, **requirements):
        if 'b' in requirements:
            self.setting = requirements['b']['setting']

    def calculate(self, state, want_derived, **params_values_dict):
        state['b'] = params_values_dict['b_param'] * self.setting
    
    def get_can_provide(self):
        return ['b']

class C(Theory):
    def must_provide(self, **requirements):
        if 'c' in requirements:
            return {'b': {'setting': 1}}
    
    def calculate(self, state, want_derived, **params_values_dict):
        state['c'] = self.provider.get_result('b')
    
    def get_can_provide(self):
        return ['c']


class JustTest(Likelihood):
    def get_requirements(self) -> InfoDict:
        return {'a': None, 'c': None, 'theta': None, 'sigma': None}

    def logp(self, **params_values):
        theta, sigma = params_values['theta'], params_values['sigma']
        a = self.provider.get_result('a')
        c = self.provider.get_result('c')
        chi2 = (theta - a)**2 / sigma**2
        print(f"theta={theta:.3f}, a={a:.3f}, c={c:.3f}")
        return -0.5 * chi2
````
YAML file:
```yaml
theory:
  mytheory.A:
    python_path: .
  mytheory.B:
    python_path: .
  mytheory.C:
    python_path: .

likelihood:
  mytheory.JustTest:
    python_path: .

params:
  theta: 20
  sigma: 0.1
  b_param: 10

sampler:
  evaluate:

output: chains/testABC
```
Output shows `a=10.000, c=10.000` instead of `a=20.000, c=10.000`.
Did I do something stupid or this is a bug?

**Comment by cmbant** [comment]
The error message looks correct - BCalculator just returns a constant independent of any sampled parameters (usually if this happens this is a mistake in any real-world case - if it were a constant you'd abolish it and replace with the constant).

The way you passed the kmax option from A to B looks fine. get_requirements returns quantities that are always needed, and must_provide takes in things this component is asked to calculate and returns conditional requirements.

In the last example, they may conflict, it depends on how the setting is used. e.g. for CAMB you can specify different lmax settings and it will combine them consistently without a problem. But if it's a global setting that is exclusive, it could conflict. It's up to the theory class implementation to handle any inconsistent requests on a case by case basis and raise errors if needed.

**Comment by zhaoruiyang98** [comment]
@cmbant 
So it's coder's responsibility to deal with conflicts and cobaya doesn't provide interface to deal with this.
Thank you very much! It's much clearer to me now.

BTW, the example in doc is not so complete and I would appreciate it if this example can be fixed and improved~😄

**Comment by cmbant** [comment]
PRs with doc improvements are welcome!
