### ISSUE TITLE
Mispell for sn.pantheon in cobaya-cosmo-generator

### ISSUE THREAD

**Issue by lbarosi** [CobayaSampler/cobaya#184]
https://github.com/CobayaSampler/cobaya/blob/c7571f4fa766aa81721423ca2e3e597f547660cc/cobaya/cosmo_input/input_database.py#L535

This is just a mispell **sn.pantheoon** ion line referenced insted of **sn.pantheon** when gererating cobaya-cosmo-generator info file.

When corrected, it works fine.

**Comment by cmbant** [comment]
Thanks, fixed in https://github.com/CobayaSampler/cobaya/commit/f6fd5c0d7582a4aad7da89899a334dd93f22db79
