### ISSUE TITLE
MPI problem on NERSC

### ISSUE THREAD

**Issue by zhaoruiyang98** [CobayaSampler/cobaya#187]
Hi,
I want to run cobaya on NERSC.
I cloned the `lazy-mpi4py` environment according to [this guide](https://docs.nersc.gov/development/languages/python/parallel-python/#mpi4py).
Then I successfully installed cobaya and cosmological code according to the documentation.
But when I ran `cobaya-run-job --job-template job_script_NERSC test.yaml`, I got the following log:
```log
[0 : output] Output to be read-from/written-into folder 'chains', with prefix 'test'
[0 : output] *ERROR* File chains/test.input.yaml.locked is locked.
You may be running multiple jobs with the same output when you intended to run with MPI. Check that mpi4py is correctly installed and configured (using the same mpi as mpirun/mpiexec); e.g. try the test at
https://cobaya.readthedocs.io/en/latest/installation.html#mpi-parallelization-optional-but-encouraged
Your current mpi4py config is:
 {'mpicc': '/opt/cray/pe/craype/2.6.2/bin/cc -shared'}
[0 : run] Aborting MPI due to error
Rank 0 [Thu Jul  8 03:07:23 2021] [c3-0c2s12n3] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
srun: error: nid00755: task 0: Aborted
srun: Terminating job step 43969283.0
slurmstepd: error: *** STEP 43969283.0 ON nid00755 CANCELLED AT 2021-07-08T03:07:23 ***
srun: error: nid00755: tasks 1-3: Terminated
srun: Force Terminated job step 43969283.0
```
I tested mpi4py following this [link](https://cobaya.readthedocs.io/en/latest/installation.html#mpi-parallelization-optional-but-encouraged) and it worked well.

I attached my job script template:
```
#!/bin/bash
#SBATCH -N {NUMNODES}
#SBATCH -q {QUEUE}
#SBATCH -J {JOBNAME}
#SBATCH -C haswell
#SBATCH -t {WALLTIME}

#OpenMP settings:
export OMP_NUM_THREADS={OMP}
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

###set things to be used by the python script, which extracts text from here with ##XX: ... ##
### command to use for each run in the batch
##RUN: module load python; source activate cobaya; module load cray-mpich; module load PrgEnv-gnu; time srun -n {NUMMPI} -c {OMP} --cpu_bind=cores {PROGRAM} {INI} > {JOBSCRIPTDIR}/{INIBASE}.log 2>&1 ##
### defaults for this script
##DEFAULT_qsub: sbatch ##
##DEFAULT_qdel: scancel ##
##DEFAULT_cores_per_node: 24 ##
##DEFAULT_chains_per_node: 4 ##
##DEFAULT_program: cobaya-run -r ##
##DEFAULT_walltime: 00:05:00##
##DEFAULT_queue: debug##

cd {ROOTDIR}

{COMMAND}

wait

```
and here is my module list:
```
  1) modules/3.2.11.4                                 13) ugni/6.0.14.0-7.0.1.1_7.54__ge78e5b0.ari
  2) altd/2.0                                         14) pmi/5.0.14
  3) darshan/3.2.1                                    15) dmapp/7.1.1-7.0.1.1_4.64__g38cf134.ari
  4) craype-network-aries                             16) gni-headers/5.0.12.0-7.0.1.1_6.43__g3b1768f.ari
  5) gcc/8.3.0                                        17) xpmem/2.2.20-7.0.1.1_4.23__g0475745.ari
  6) craype/2.6.2                                     18) job/2.2.4-7.0.1.1_3.50__g36b56f4.ari
  7) cray-mpich/7.7.10                                19) dvs/2.12_2.2.167-7.0.1.1_17.6__ge473d3a2
  8) craype-haswell                                   20) alps/6.6.58-7.0.1.1_6.22__g437d88db.ari
  9) craype-hugepages2M                               21) rca/2.2.20-7.0.1.1_4.65__g8e3fb5b.ari
 10) python/3.8-anaconda-2020.11                      22) atp/2.1.3
 11) cray-libsci/19.06.1                              23) PrgEnv-gnu/6.0.5
 12) udreg/2.3.2-7.0.1.1_3.52__g8175d3d.ari
```
Did I miss something?

**Comment by cmbant** [comment]
Not sure, maybe an issue with the cray setup/srun? I think the more vanilla setup shown in https://cobaya.readthedocs.io/en/latest/run_job.html#job-script-templates does work (at least one person recently).

Basically the error is trying to trap mismatches between mpi version in mpi4py and mpi version when using mpiexec/srun. You could do simple test MPI program and see if mpi4py reports more than mpi size one.

**Comment by zhaoruiyang98** [comment]
Yes I did the following test
```sh
#!/bin/bash
#SBATCH -N 1
#SBATCH -q debug
#SBATCH -J mpidebug
#SBATCH -C haswell
#SBATCH -t 00:01:00

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

srun -n 4 python -c "from mpi4py import MPI; print(MPI.COMM_WORLD.Get_rank())"
```
It prints `0,1,2,3` as expected.

**Comment by cmbant** [comment]
Though not importing all the envs of your cobaya one?  I assume you have portalocker installed via pip cobaya install?
________________________________

**Comment by zhaoruiyang98** [comment]
Yes, I installed everything (mpi4py, portalocker, cobaya, etc...) in a conda environment.
I activate this conda environment in .bashrc file and it seems like this file will be automatically sourced when I submit my job script.
This is just a simple test :-)

**Comment by cmbant** [comment]
Does it work if you do the "source activate cobaya; module load cray-mpich; module load PrgEnv-gnu;" as in your cobaya script?

**Comment by zhaoruiyang98** [comment]
No, it still doesn't work and output the same error message...

**Comment by cmbant** [comment]
If your simple also test doesn't work with that, then the issue is not with cobaya but in your job script settings/config. 
Play with the output submitted script in Scripts/, replacing cobaya-run with your
```python -c "from mpi4py import MPI; print(MPI.COMM_WORLD.Get_rank())"```
and change the config until it works.

**Comment by zhaoruiyang98** [comment]
I successfully run cobaya on another cluster with similar settings. 
Therefore the issue is indeed in my job script settings/config on NERSC.
Since NERSC is now under maintenance, I will update this issue if I find the way to fix this.

Thank you for your help and your patience!
