### ISSUE TITLE
MPI is not being initialized for SLUMP 

### ISSUE THREAD

**Issue by dwhan89** [CobayaSampler/cobaya#19]
Thanks for writing and sharing Cobaya. This is a great software! I have found a minor bug that I am reporting below

------

* cobaya version: 0.126
* Python version: 2.7.13
* Operating System: SuSE Linux Enterprise Server (SLES) Linux distribution (NERSC Cori Cluster)

### Description

On NERSC Cori Cluster, `mpirun` command is disabled. Instead, it has its SLURM counterpart called `srun`. Unfortunately, SLURM has its own set of enviromental variables.  So when I try to do a MPI run with `srun`, Cobaya isn't MPI aware.  I think the issue is with the following code block under `mpi.py`, which looks for specific MPI variables.
```
        if any([os.getenv(v) for v in
                ["OMPI_COMM_WORLD_SIZE",  # OpenMPI
                 "PMI_SIZE"]]):           # Inte MPI
            from mpi4py import MPI
            _mpi = MPI
        else:
            _mpi = None
```

### What I Did

For now, I have implemented the following workaround. 

```
    if _mpi == -1:
        try:
            from mpi4py import MPI
            _mpi = MPI
        except:
            _mpi = None
```

**Comment by JesusTorrado** [comment]
Hi @dwhan89 

You should be able to use the last commit as is. Please, let me know if it works and whether you observe any unexpected side effect.

At some point, I intended to create a doc page similar to the one for the Amazon Cloud (https://cobaya.readthedocs.io/en/latest/cluster_amazon.html), summarizing the non-trivial necessary configuration steps for Cori, but never got around to do it. If you have the time to write such a summary, I would be very grateful and happy to include it in the docs with you as the author, of course.

Cheers
Jesús

**Comment by dwhan89** [comment]
Hi, @JesusTorrado 

Thanks for the fast fix! I will close the issue now. 

And, sure, I am happy to help you with the summary page. So far, everything ran as I expected, except this minor bug. I will let you know if I find any other Cori related quirks.

Cheers!
DW

**Comment by JesusTorrado** [comment]
Hi @dwhan89 

If everything works as expected, then there is no need to create a special page for Cori. Did you have to follow the instructions at http://www.nersc.gov/users/data-analytics/data-analytics-2/python/anaconda-python/#buildingmpi4py ? I remember needing to do it if I wanted to use GNU compilers, but maybe I was not doing things right.
