### ISSUE TITLE
No progress update when `learn_proposal_Rminus1_min > 0`

### ISSUE THREAD

**Issue by lukashergt** [CobayaSampler/cobaya#194]
Naively I would have thought that setting the MCMC parameter `learn_proposal_Rminus1_min` to something greater than zero will only affect whether the covariance matrix is being learned or not. I was surprised to find that it also stops any information being printed to the `.progress` file once the given threshold is reached.

Is that intentional? If so, it might be good to add a little warning to the documentation which only refers to the covariance learning:

> ```yaml
> # Proposal covariance matrix learning
> # -----------------------------------
> learn_proposal: True
> # Don't learn if convergence is worse than...
> learn_proposal_Rminus1_max: 2.
> # (even earlier if a param is not in the given covariance matrix)
> learn_proposal_Rminus1_max_early: 30.
> # ... or if it is better than... (no need to learn, already good!)
> learn_proposal_Rminus1_min: 0.
> ```

But it would probably be nicer to keep updating the `.progress` file even when the covariance matrix stops updating.

**Comment by lukashergt** [comment]
Seems to have been fixed, so closing this.

**Comment by JesusTorrado** [comment]
Thanks, @lukashergt !
