### ISSUE TITLE
Conversion between logAs and As

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#2]
Hello!

Thanks for all support so far. I have a new issue. When I type

`
params:
  logA:
    prior: {min: 2, max: 4}
    ref: {dist: norm, loc: 3.1, scale: 0.001}
    proposal: 0.001
    latex: \log(10^{10} A_\mathrm{s})
    drop: true
  As: 
    value: 'lambda logA: 1e-10*np.exp(logA)' 
    latex: 'A_\mathrm{s}'
`

everything works perfectly, but when I try to fix logAs, Cobaya does not make the conversion

`
params:
  logA:
    value: 3.11820385633
  As: 
    value: 'lambda logA: 1e-10*np.exp(logA)' 
    latex: 'A_\mathrm{s}'
`

Error message:

> *ERROR* Some of the parameters passed to CAMB were not recognized: Unrecognized parameters: set(['logA'])

Is it possible to fix this?

**Comment by JesusTorrado** [comment]
Hi Vivian,

This was indeed not implemented. It should work after https://github.com/CobayaSampler/cobaya/commit/5e69e3b7f5b0502c73131e4c17f54cee55b508ef, provided that you add a `drop: True` to the `logA` definition (otherwise, it will pass it to CAMB).

Let me know if it works as intended, please.

**Comment by vivianmiranda** [comment]
Hi

It did work!

Thank you!



On Nov 12, 2018, at 7:02 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vivian,

This was indeed not implemented. It should work after 5e69e3b<https://github.com/CobayaSampler/cobaya/commit/5e69e3b7f5b0502c73131e4c17f54cee55b508ef>, provided that you add a drop: True to the logA definition (otherwise, it will pass it to CAMB).

Let me know if it works as intended, please.

**Comment by vivianmiranda** [comment]
Sorry

I sent the picture the wrong thread

Your As fit broke something

[cid:93AAF31A-B0CA-4A2C-80C1-DADA32008024@arizona.edu]

On Nov 12, 2018, at 7:02 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vivian,

This was indeed not implemented. It should work after 5e69e3b<https://github.com/CobayaSampler/cobaya/commit/5e69e3b7f5b0502c73131e4c17f54cee55b508ef>, provided that you add a drop: True to the logA definition (otherwise, it will pass it to CAMB).

Let me know if it works as intended, please.
