### ISSUE TITLE
change range of ell and in Planck 2018 likelihood

### ISSUE THREAD

**Issue by taladi** [CobayaSampler/cobaya#210]
I wish to use Planck TT likelihood in a specific range of multipoles and not sure how to do that. Is it done directly from the input yaml file?  What is the syntax that should be used, for example for using TT for ell<1500?

Thanks!

**Comment by Xx-Luffy-xX** [comment]
How may I do that? Do you have an example at hand?

Thanks.

**Comment by cmbant** [comment]
Not for clik.

**Comment by Xx-Luffy-xX** [comment]
Figured it out, thanks anyway!
