### ISSUE TITLE
Use CLASS with different precision parameters (e.g. "cl_ref.pre")

### ISSUE THREAD

**Issue by talabadi** [CobayaSampler/cobaya#212]
I know that when running CLASS one may use two inputs, for example:
`./class input_file.ini cl_ref.pre`
in order to play with the precision of the code, but how to include such "cl_ref.pre" in the Cobaya run?

Do I need to copy all the parameters in the .yaml file as "extra arguments", or is there a way to refer to the .pre file?

Thanks!

**Comment by JesusTorrado** [comment]
You need to copy all the parameters as extra arguments. If you are going to do this often, you may e.g. build the input info of Cobaya programmatically, and call it from a .py script.

**Comment by talabadi** [comment]
Thanks!
