### ISSUE TITLE
IntelMPI job template

### ISSUE THREAD

**Issue by runburg** [CobayaSampler/cobaya#214]
Hello,

Is there anywhere on the docs that has a job template for IntelMPI (vs. OpenMPI)? I've created some sort of Frankenstein's monster template by combining example scripts from my local cluster with the OpenMPI job template from the docs.

Unfortunately, I keep getting an error 
```
slurmstepd: error: execve(): cobaya-run: No such file or directory
srun: error: node-0260: tasks 0-19: Exited with exit code 2
```

If I run the cobaya-run command with my yaml file it works, but for some reason `srun -n 4 cobaya-run -r [my_file].yaml` doesn't work...

**Comment by cmbant** [comment]
Not sure, though looks more like a path issue?
