### ISSUE TITLE
BestFit Chi^2 values for CamSpec 12.6 version

### ISSUE THREAD

**Issue by ndb0** [CobayaSampler/cobaya#216]
Hi,
 I am running cobaya for an inflationary model, with these two sets of likelihoods for CamSpec2021 or CamSpec 12.6 version :

likelihood:
  planck_2018_lowl.TT: null
  planck_2018_lowl.EE: null
  planck_2018_highl_CamSpec2021.TT: null

likelihood:
  planck_2018_lowl.TT: null
  planck_2018_lowl.EE: null
  planck_2018_highl_CamSpec2021.TTTEEE: null

I was wondering if best-fit Lcdm reference values of chi^2 for these lwo likelihoods are available somewhere. From Planck legacy data cite the best-fit values are quoated for CamSpec 10.7 version but I could not find any values for 12.6 or 12.5 version. Any information in this regard shall be very helpful.
Thanks in advance.

**Comment by cmbant** [comment]
There is a 2021 CAMspec test in https://github.com/CobayaSampler/cobaya/blob/master/tests/test_cosmo_planck_2018.py
