### ISSUE TITLE
Including WMAP likelihood through Clik

### ISSUE THREAD

**Issue by valadur19** [CobayaSampler/cobaya#229]
Just started using the Cobaya sampler and I am interested in making use of WMAP's likelihood through the clik wrapper, similar to what Montepython seems to offer through a 'clik' type likelihood. Is it possible to use ['Interface for official clik code'](https://cobaya.readthedocs.io/en/latest/likelihood_planck.html?highlight=clik%20#module-planck_clik) for this purpose? The documentation does not expand too much.

**Comment by cmbant** [comment]
You can use the clik wrapper, but there's no specific wrapper for WMAP do you'd have to write the class to do that yourself
