### ISSUE TITLE
Change l_max with Planck Likelihood

### ISSUE THREAD

**Issue by KunhaoZhong** [CobayaSampler/cobaya#234]
Hi,

I'm just wondering what could be the best way to adjust l_max requirement for Planck likelihood. It seems less intuitive than, for example, in bicep_keck_2015.yaml.

I noticed there's an "lmax" file in the .clik file, but how do we change it, and how to make sure the modified likelihood is properly installed?

**Comment by cmbant** [comment]
You would need to read the clik documentation
