### ISSUE TITLE
Getting error "AttributeError: Cannot set theory attribute for custom_likelihood!" when making my own likelihood class

### ISSUE THREAD

**Issue by mmsh-um** [CobayaSampler/cobaya#238]
I'm new to Cobaya. I'm trying to write my own likelihood to be able to run MCMC chains. My data comprises pairs of means of DM/rs and DH/rs at various redshifts and the covariances at each redshift. The skeleton of the code I have is the following:

`
from cobaya.likelihood import Likelihood
import numpy as np
import os

class custom_likelihood(Likelihood):

    def initialize(self):
        """
         Prepare any computation, importing any necessary code, files, etc.
        """
   # Here I import my files needed: the data vectors and covariance matrices. Code not attached

    def get_requirements(self):
        """
         return dictionary specifying quantities calculated by a theory code are needed
         
        """
        zs = self.z
    
        theory_vals = {"angular_diameter_distance": {"z": zs}, "Hubble": {"z": zs}}
        return theory_vals

    def logp(self, **params_values):
        """
        Taking a dictionary of (sampled) nuisance parameter values params_values
        and return a log-likelihood.
        """
      
       # Here I calculate theoretical values of DH/rs and DM/rs that I need for loglkl

        for i in range(self.num_bins):
            theo_DH_rs = self.provider.get_Hubble(z[i], units="km/s/Mpc") * self.rs()

            theo_DM_rs = (1 + self.z[i]) * self.provider.get_angular_diameter_distance(z[i]) / self.rs()
            
   
        chi2 = ...

        # return ln(L)
        loglkl = - 0.5 * chi2

    
        return loglkl
`

Regardless of what I include in the logp or get_requirements blocks, I keep getting the following error:

`[output] Output to be read-from/written-into folder '.', with prefix 'custom_likelihood'
[output] Found existing info files with the requested output prefix: 'custom_likelihood'
[classy] Importing *auto-installed* CLASS (but defaulting to *global*).
[classy] Initialized!
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cobaya/component.py", line 88, in __init__
    setattr(self, k, value)
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
  File "/usr/local/lib/python3.9/site-packages/cobaya/run.py", line 216, in run_script
    run(info, **arguments.__dict__)
  File "/usr/local/lib/python3.9/site-packages/cobaya/run.py", line 134, in run
    with Model(updated_info["params"], updated_info["likelihood"],
  File "/usr/local/lib/python3.9/site-packages/cobaya/model.py", line 152, in __init__
    self.likelihood = LikelihoodCollection(info_likelihood, theory=self.theory,
  File "/usr/local/lib/python3.9/site-packages/cobaya/likelihood.py", line 298, in __init__
    self.add_instance(name, like_class(info, packages_path=packages_path,
  File "/usr/local/lib/python3.9/site-packages/cobaya/likelihood.py", line 90, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/usr/local/lib/python3.9/site-packages/cobaya/theory.py", line 65, in __init__
    super().__init__(info, name=name, timing=timing,
  File "/usr/local/lib/python3.9/site-packages/cobaya/component.py", line 90, in __init__
    raise AttributeError("Cannot set {} attribute for {}!".format(k, self))
AttributeError: Cannot set theory attribute for custom_likelihood!`

I would appreciate some help with how to fix this. I'm not sure what's causing this.

**Comment by cmbant** [comment]
Perhaps an indentation error in your input yaml? You could of course use/override the provided BAO classes.

**Comment by mmsh-um** [comment]
Thanks! I was able to solve it by removing the theory block completely from the .yaml file.

At the moment, I'm facing this:
`[output] Output to be read-from/written-into folder '.', with prefix 'custom_likelihood'
[output] Found existing info files with the requested output prefix: 'custom_likelihood'
[model] *ERROR* Requirement angular_diameter_distance of custom_likelihood is not provided by any component, nor sampled directly
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/cobaya-run", line 8, in <module>
    sys.exit(run_script())
  File "/usr/local/lib/python3.9/site-packages/cobaya/run.py", line 216, in run_script
    run(info, **arguments.__dict__)
  File "/usr/local/lib/python3.9/site-packages/cobaya/run.py", line 134, in run
    with Model(updated_info["params"], updated_info["likelihood"],
  File "/usr/local/lib/python3.9/site-packages/cobaya/model.py", line 159, in __init__
    self._set_dependencies_and_providers(skip_unused_theories=skip_unused_theories)
  File "/usr/local/lib/python3.9/site-packages/cobaya/model.py", line 613, in _set_dependencies_and_providers
    raise LoggedError(self.log,
cobaya.log.LoggedError: Requirement angular_diameter_distance of custom_likelihood is not provided by any component, nor sampled directly`

What does the requirement not being provided by any component mean? I'm merely trying to calculate the angular_diameter_distance at certain redshifts, as is done in the code I pasted in my previous post in this thread.

I had considered using the BAO class (which I am using as inspiration to write my own either way) but it looks like the BAO class was written with having one big covariance matrix in mind. I have 2x2 covariances at each redshift (for the DM/rs and DH/rs at each) and I wasn't sure of how to combine that information.

**Comment by mmsh-um** [comment]
I'm wondering if the above error is because of taking out the 'theory' part entirely from the .yaml. But when I keep it in there, I cannot see where an indentation error may be coming from.

This is my .yaml:

`likelihood: 
 custom_likelihood: 
  python_path: '/path/to/Cobaya_Directory/custom_likelihood'

params: 
 omega_b: 
  prior: 
   min: 0.005
   max: 0.1
  ref: 
   dist: norm
   loc: 0.0224
   scale: 0.0001
  proposal: 0.0001
 
sampler: 
 mcmc: 
  drag: true
  oversample_power: 0.4
  proposal_scale: 1.9
  Rminus1_stop: 0.01
  Rminus1_cl_stop: 0.2

theory: 
 classy: 
  extra_args: 
   N_ncdm: 1
   N_ur: 2.0328`

**Comment by cmbant** [comment]
Looks OK. Please attach your full code/reproducing example.

**Comment by mmsh-um** [comment]
This is the likelihood .py file I wrote:

`from cobaya.likelihood import Likelihood
import numpy as np
import os

numpts = 20
class custom_likelihood(Likelihood):

    def initialize(self):
        """
         Prepare any computation, importing any necessary code, files, etc.
        """

        # define arrays for values of z and data points
        self.z = np.array([], 'float64')
        self.DH_rs = np.array([], 'float64')
        self.DM_rs = np.array([], 'float64')
        self.fsig8 = np.array([], 'float64')

        self.data_directory = "/path/to/data.txt"
        # read redshifts and data points
        with open(self.data_directory, 'r') as filein:
            for i, line in enumerate(filein):
                if line.strip() and line.find('#') == -1:
                    this_line = line.split()
                    if this_line[1] == 'fsig8':
                        self.z = np.append(self.z, float(this_line[0]))
                        self.fsig8 = np.append(self.fsig8, float(this_line[2]))
                    elif this_line[1] == 'dM(rsfid/rs)':
                        self.DH_rs = np.append(
                            self.DH_rs, float(this_line[2]))
                    elif this_line[1] == 'dV(rs/rsfid)':
                        self.DM_rs = np.append(
                            self.DM_rs, float(this_line[2]))

        self.cov_data = {}
        self.data_directory = "/path/to/covariancematrices"
        
        for i in range(numpts):
            zval = self.z[i]

            suffvar = "cov_all_%s.txt"%zval
            self.cov_data[i] = np.loadtxt(os.path.join(self.data_directory, suffvar))[1:3,1:3]

            # number of bins
        self.num_bins = np.shape(self.z)[0]
    
            # number of data points
        self.num_points = numpts*np.shape(self.cov_data[1])[0]


    def get_requirements(self):
        """
         return dictionary specifying quantities calculated by a theory code are needed
         
        """
        zs = self.z
        print(zs)
 
        theory_reqs = {"angular_diameter_distance": {"z": zs}, "Hubble": {"z": zs}}
        return theory_reqs

    def logp(self, **params_values):
        """
        Taking a dictionary of (sampled) nuisance parameter values params_values
        and return a log-likelihood.
        """
        rs_d = 148 
        opts = np.shape(self.num_bins)
        data_array = {}
        for i in range(self.num_bins):
            data_array[i] = np.array([0,0], 'float64')
        for i in range(self.num_bins):
            theo_DH_rs = self.provider.get_Hubble(z[i], units="km/s/Mpc") / rs_d

            theo_DM_rs = (1 + self.z[i]) * self.provider.get_angular_diameter_distance(z[i]) / rs_d
            

            # calculate difference between the sampled point and observations
            DH_diff = theo_DH_rs - self.DH_rs[i]
            DM_diff = theo_DM_rs - self.DM_rs[i]

            # save to data array

            data_array[i][0] = DH_diff
            data_array[i][1] = DM_diff


          

        inv_cov_data = {}

        # compute chi squared

        for t in range(numpts):
            inv_cov_data[t] = np.linalg.inv(self.cov_data[t])

        chi2 = 0
        for k in range(numpts):
            chi2 = np.sum([chi2,np.dot(np.dot(data_array[k], inv_cov_data[k]), data_array[k])])  

        # return ln(L)
        loglkl = - 0.5 * chi2


    
        return loglkl
`

**Comment by cmbant** [comment]
Please can you zip everything to reproduce your "theory "error message - including input files/yaml etc for use with cobaya-run (or a complete jupyter notebook)

**Comment by cmbant** [comment]
can you provide a reproducing example?

**Comment by cmbant** [comment]
Closing for now, please reopen if you have a full example to reproduce
