### ISSUE TITLE
MPI error of waiting too long for chain(s) if running on multiple nodes, and more than one chain per node

### ISSUE THREAD

**Issue by MinhMPA** [CobayaSampler/cobaya#241]
Hi,

I'm having this MPI issue on our UMich Greatlakes cluster, that I think might be trivial and more because of me running `cobaya` in a way that it's not supposed to be run. But here it is:

I get this MPI error if I try to `mpirun` on more than one node, wherein more than one chain is run on each node. For example,

```
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=2
```

and

```
mpirun -n 4 cobaya-run [path to gaussian_example.yaml]
```

results into

```
[1 : mcmc] *ERROR* Waiting for too long for all chains to be ready. Maybe one of them is stuck or died unexpectedly?
[1 : mcmc] Aborting MPI due to error
```

However, if I run 4 chains on one single node, or 4 chains on 4 nodes, then all chains run successfully, using the same `mpirun` and `cobaya` setup.

**Comment by cmbant** [comment]
It should work across multiple nodes. Closing for the moment, please reopen if there's a reproducible issue.
