### ISSUE TITLE
How to get low-E TE likelihoods for Planck? 

### ISSUE THREAD

**Issue by mmsh-um** [CobayaSampler/cobaya#242]
I am running chains for the Planck likelihoods described here: https://cobaya.readthedocs.io/en/latest/likelihood_planck.html

I that we are given, for example, the planck_2018_lowl.TT likelihood. But I can't see how to separately have TE instead. I would like to replicate some plots from the official Planck 2018 paper. I see under the Native CamSpec version section that it says: "Use dataset_params : { ‘use_cl’: ‘100x100 143x143 217x217 143x217’} to use e.g. just TT , or other combination with TE and EE." 
Would that be how it's done? I'm unsure of how exactly I'm supposed to call this. Or would I need to set up my own likelihoods instead of using the ones that are already installed? Thanks!

**Comment by cmbant** [comment]
This sounds like a question for cosmocoffee, not a bug
