### ISSUE TITLE
Cobaya's verification of CLASS python wrapper version fails

### ISSUE THREAD

**Issue by valadur19** [CobayaSampler/cobaya#243]
When using CLASS within an Anaconda environment for python 3.9 (probably also happens for other >3.0 versions) the build produces a lib.******39*** file which fails cobaya's test on the python version of CLASS because it looks for a file lib.****3.9*** 

See the line 508 of classy.py 

Although CLASS is properly compiled and its python wrapper works, Cobaya does not start sampling if this test fails.

**Comment by JesusTorrado** [comment]
Hi @valadur19 

Could you please try again after the last commit? (https://github.com/CobayaSampler/cobaya/commit/228ebf3f148e8fc39013e454236521858ad4c550)

**Comment by JesusTorrado** [comment]
Appears to work with some basic tests. Please reopen if needed.
