### ISSUE TITLE
MPI error when submitting a job with mpirun (and a solution)

### ISSUE THREAD

**Issue by borisbolliet** [CobayaSampler/cobaya#244]
Hi, 

When I submit a job (at NERSC/Cori) with:

`$ salloc -N 4 -C haswell -q interactive -t 04:00:00 -c 64 mpirun -np 4 cobaya-run my_test.yaml -f`

I get the error:

> [0 : output] *ERROR* File my_test.input.yaml.locked is locked.
> You may be running multiple jobs with the same output when you intended to run with MPI. Check that mpi4py is correctly installed and configured (using the same mpi as mpirun/mpiexec); e.g. try the test at
> https://cobaya.readthedocs.io/en/latest/installation.html#mpi-parallelization-optional-but-encouraged
> Your current mpi4py config is:
>  {'mpicc': '/global/common/software/m3169/cori/openmpi/4.1.2/intel/bin/mpicc'}
> [0 : run] Aborting MPI due to error

Nonetheless, I don't get any error when I launch the calculation on the head node, with just:

`mpirun -np 4 cobaya-run my_test.yaml -f`

I was able to fix the error in the job submission by commenting out the following line: https://github.com/CobayaSampler/cobaya/blob/ab57412ac057f3d7f8d70ea48d0268ea84737e1f/cobaya/output.py#L70

Also, my mpirun and mpi4py are indeed configured with the same mpi (as above, the nersc one). 

(Not sure if this is related to #241? but maybe worth trying something along these lines too @MinhMPA).

I didn't have that problem a couple of weeks ago, but encountered it when I updated all my codes to latest versions (Cobaya+classy). This may well be due to some NERSC mpi update too... and we should close the issue if so...

Thank you for the great code!

**Comment by cmbant** [comment]
c.f https://github.com/CobayaSampler/cobaya/issues/215 https://github.com/CobayaSampler/cobaya/issues/219

**Comment by borisbolliet** [comment]
Great! thank you... ah I should have checked more carefully the issues...
