### ISSUE TITLE
New likelihood not being sampled/used?

### ISSUE THREAD

**Issue by runburg** [CobayaSampler/cobaya#245]
I wrote my own likelihood that is just calculating a simple chi2 between the computed Cls and a set of fiducial Cls (with error bars) that I modeled off of the the example in the docs.

However, when I run cobaya with my likelihood and planck likelihoods, my likelihood doesn't change the posteriors. No matter how small I make my error bars, the posteriors never change which seems wrong to me. I wanted to try a run with just my likelihood to make sure that things are working, but when I try this I get:

```Covariance matrix selected automatically: {packages_path}/data/planck_supp_data_and_covmats/covmats/BKPlanck.covmat
[0 : mcmc] *ERROR* A proposal covariance matrix has been loaded, but none of its parameters are actually sampled here. Maybe a mismatch between parameter names
 in the covariance matrix and the input file?
```

I'm not sure what this means and is maybe related to my likelihood not affecting the posteriors?

For reference, my likelihood looks like:
```
class cmb_chi2(Likelihood):
    """Return chi2 for fiduial CMB"""
    def initialize(self):
        self.ells, self.Cls, self.Cls_err = np.loadtxt(self.cl_file).T

    def get_requirements(self):
        return {'Cl': {'pp': self.ells.max().astype(int)}}

    def logp(self, **param_values):
        Cls = self.provider.get_Cl(ell_factor=False, units="muK2")
        ells = np.arange(l_max+1)
        Cl_est = Cls['pp'][:l_max + 1]
        cl_interp = interp1d(ells, Cl_est)
        cls_lik = cl_interp(self.ells)
        chi2 = ((self.Cls - cls_lik)**2 / self.Cls_err**2).sum()
        return -chi2 / 2
```

**Comment by cmbant** [comment]
Sounds like it is not being called. Probably need more details of the full script/yaml. Does your likelihood appear in the dependency in the output log.

**Comment by runburg** [comment]
In the yaml file it is being loaded in the likelihood block:

```
likelihood:
  cmb_likelihood.cmb_chi2:
    python_path: '/home/runburg/neutrinos_and_dm'
    cl_file: '/home/runburg/neutrinos_and_dm/our_lld_only/fiducial_power_spectrum.txt'
    stop_at_error: True
```

The log tests the speed which I have been assuming means it is called:

```
[0 : model] Setting measured speeds (per sec): {cmb_likelihood.cmb_chi2: 980.0, classy: 0.0964}
```

**Comment by cmbant** [comment]
Please could you send a zip of full source to reproduce the issue, using camb rather than classy? (assuming that is still a problem with camb)

**Comment by runburg** [comment]
Hi, I tried using camb on my laptop and there are no issues. I also tried using classy on my laptop and I can get things to work.

However, when I go through the same exercise with my installation on HPC I am encountering the same error. 
```
0 : model] Setting measured speeds (per sec): {cmb_s4_chi2.cmb_s4_chi2: 833.0, classy: 0.119}
[0 : mcmc] Covariance matrix selected automatically: {packages_path}/data/planck_supp_data_and_covmats/covmats/BKPlanck.covmat
[0 : mcmc] *ERROR* A proposal covariance matrix has been loaded, but none of its parameters are actually sampled here. Maybe a mismatch between parameter names in the covariance matrix and the input file?
```
When I run on my local machine, it doesn't try and default to one of the planck covariance matrices. I'm a little mystified about why this is the case. I've the same `params` block in both yaml files. In one case (on my laptop), `cobaya` says it will try to learn the covmat but on the HPC installation is tries to default to a planck covmat and then fails.

Any ideas? Is there an alternative to `covmat: auto` that would try to learn the covariance matrix without trying to find one that already exists within cobaya?

**Comment by runburg** [comment]
Okay so after removing `covmat: auto` I can get cobaya to try and learn the covariance matrix so I think that was the problem I was seeing before. Likelihood evaluations seem to be working. 

It's still not clear to me why there is a difference in behaviors between my different installations. I'll close this unless you need more information.
