### ISSUE TITLE
Error when using external power spectra with CLASS in Cobaya

### ISSUE THREAD

**Issue by Ameek94** [CobayaSampler/cobaya#246]
Is it possible to use the external_Pk method of CLASS with Cobaya? I would like to do something similar to the example you presented [here](https://github.com/CobayaSampler/paper_cosmo_demo) where you used an external file to generate the primordial power spectrum to be passed on to CAMB. Only difference being that I would like to use CLASS.

I tried by adding the following to the theory block of my .yaml file
```
theory:
  classy:
    extra_args:
      modes: s,t
      lensing: yes
      Pk_ini_type: external_Pk
      command: python external_pk_tensor.py 
      non linear: halofit
```
'external_pk_tensor.py' is my external file which generates the scalar and tensor power spectrum, same as the CLASS [documentation](https://github.com/lesgourg/class_public/tree/master/external/external_Pk).

When I do a test run of Cobaya with these settings the included likelihoods are initialised successfully but then I get the following error from CLASS -

```
[classy] *ERROR* Serious error setting parameters or computing results. 
The parameters passed were {'custom1': 0.05, 'custom2': 2.1140160094071228e-09, 
'custom3': 0.9690508214946489, 'custom4': 0.010091748826901654, 'custom5': -0.023736197164283872, 'H0': 67.32117, 'omega_b': 0.0223828, 
'N_ur': 2.046, 'omega_cdm': 0.1201075, 'N_ncdm': 1.0, 'm_ncdm': 0.06, 'T_ncdm': 0.713765855503608, 
'YHe': 0.2454006, 'tau_reio': 0.05430842} and {'modes': 's,t', 'lensing': 'yes', 'Pk_ini_type': 'external_Pk',
'command': 'python external_pk_tensor.py', 'non linear': 'halofit', 'output': 'lCl tCl pCl', 'l_max_scalars': 2700}. 
To see the original CLASS' error traceback, make 'debug: True'.
2022-06-02 16:36:46,290 [classy] Ignored error at evaluation and assigned 0 likelihood 
(set 'stop_at_error: True' as an option for this component to stop here and print a traceback). 
Error message: CosmoSevereError('Class did not read input parameter(s): custom1, custom2, custom3, custom4, custom5, Pk_ini_type, command\n')
```

I checked that I am able to run CLASS directly in a jupyter notebook with the same settings and can also run Cobaya if I use the default analytic_Pk method of CLASS instead of the external_Pk.  Not sure how to fix this and would appreciate your help here. I can also add the source files and full debug output if needed.

**Comment by lukashergt** [comment]
Hi @Ameek94,

what version of CLASS are you using together with Cobaya? Your setup should work in principle, but if you are using an earlier CLASS version, then it is not `Pk_ini_type`, but `P_k_ini type`...

This has worked for me in the past for Cobaya 3.0.4 with CLASS 2.9.4:

```yaml
theory:
  classy:
    extra_args:
      non linear: halofit
      N_ncdm: 1
      N_ur: 2.0328
      P_k_ini type: external_Pk
      command: python generate_PPS.py
      modes: s t
```

**Comment by Ameek94** [comment]
Hi @lukashergt,

This might have been the issue, I don't have the old version of CLASS anymore but on the newer versions ones this setup works fine with `Pk_ini_type`. 

Thanks for your help!
