### ISSUE TITLE
Total reported chi Square inconsistent

### ISSUE THREAD

**Issue by juan-s-cruz** [CobayaSampler/cobaya#247]
I am having trouble interpreting the reported total chi square by the minimizer. I have performed standard runs for LCDM using Planck, BAO and SN, among others, all outputting `{prefix}.bestfit` files where the total, printed in the second line, does not agree with the sum of the individual likelihoods reported at the bottom of the table. The difference is not a constant and varies between runs with different likelihoods. Is this a known issue?

**Comment by cmbant** [comment]
It is probably the value from the priors.

**Comment by juan-s-cruz** [comment]
How can I understand this when the setting `ignore_priors` is set to `True`?

**Comment by cmbant** [comment]
Does cobaya use anything called "ignore_priors " - where?

**Comment by juan-s-cruz** [comment]
There is a setting when using the minimizer as stated in the documentation
https://cobaya.readthedocs.io/en/latest/sampler_minimize.html

**Comment by cmbant** [comment]
I think that just changes what is minimized, not what is output

**Comment by juan-s-cruz** [comment]
So what I gather from this is that the line `chi-sq` in the files produced does not correspond only to the sum of the chi square values for the different likelihoods and includes information from my e.g. non-flat priors, now it makes sense, thanks.
