### ISSUE TITLE
Changes in naming conventions with modified CLASS

### ISSUE THREAD

**Issue by juan-s-cruz** [CobayaSampler/cobaya#248]
With the latest cobaya there seems to be a problem with modified CLASS's . If the modified one is used via the 'ignore_obsolete' option it can still happen that older classes expect args such as 'non linear' instead of the apparently now preferred 'non_linear' and Cobaya won't start sampling. Is there a work around for this? Assuming I do not want to modify, the CLASS I am using?

**Comment by JesusTorrado** [comment]
Close. Please, reopen if this is still relevant, and provide a minimal working example that can be run with a newer and older version of CLASS to observe the difference in behaviour.
