### ISSUE TITLE
Incorrect chi2 calculation in BAO 2D and 3D grid likelihoods?

### ISSUE THREAD

**Issue by seshnadathur** [CobayaSampler/cobaya#249]
The BAO grid likelihood files bundled in the data download (i.e., the SDSS DR16 ELG, LYAUTO and LYxQSO likelihood files) all provide the likelihood ratio at each point in the grid. In [bao.py](https://github.com/CobayaSampler/cobaya/blob/master/cobaya/likelihoods/base_classes/bao.py) the log of this likelihood ratio is interpolated over the grid – e.g. in [lines 263-266](https://github.com/CobayaSampler/cobaya/blob/master/cobaya/likelihoods/base_classes/bao.py#L263). This quantity is referred to as `chi2` in the code, but it is surely `-dchi2 / 2`.

Later, when computing the log probability, the interpolated value is divided by 2 again (e.g. in [line 416](https://github.com/CobayaSampler/cobaya/blob/master/cobaya/likelihoods/base_classes/bao.py#L416)), thus what is actually being returned is 1/2 times the log likelihood ratio, or `-dchi2 / 4`. The extraneous factor of 1/2 should not be there.

These likelihoods are less constraining than the LRG BAO one (especially so for the ELG likelihood), so if they are used in combination with this or other likelihoods the net effect of this factor of 1/2 on inferred cosmological params could be small. But it will affect analyses looking at constraints from the Lyman-alpha results in isolation.

**Comment by cmbant** [comment]
https://github.com/CobayaSampler/cobaya/pull/250

**Comment by cmbant** [comment]
Should now be fixed, thanks!
