### ISSUE TITLE
Error message while installing planck_2018_lowl.TT likelihood

### ISSUE THREAD

**Issue by pribamello** [CobayaSampler/cobaya#255]
Hello, 
I'm trying to install cobaya likelihoods on my OS, ubuntu 20.04, by running the command `cobaya-install cosmo -p /path/to/packages`, but it seems that it's unable to properly install  the planck_2018_lowl.TT likelihood. The following error message keeps appearing:

```

================================================================================
likelihood:planck_2018_lowl.TT
================================================================================

[install] Checking if dependencies have already been installed...
[install] Check found no existing installation
[install] (If you expected this to be already installed, re-run `cobaya-install` with --debug to get more verbose output.)
[install] Installing...
[planck_2018_lowl.TT] Installing the clik code.
[clik] Installing pre-requisites...
Requirement already satisfied: cython in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (0.29.32)
Requirement already satisfied: astropy in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (4.3.1)
Requirement already satisfied: importlib-metadata in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from astropy) (4.12.0)
Requirement already satisfied: numpy>=1.17 in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from astropy) (1.21.6)
Requirement already satisfied: pyerfa>=1.7.3 in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from astropy) (2.0.0.1)
Requirement already satisfied: zipp>=0.5 in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from importlib-metadata->astropy) (3.8.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from importlib-metadata->astropy) (4.3.0)
[clik] Downloading...
2.26MiB [00:12, 187kiB/s]                                                                                                                                                                                  
[clik] Downloaded filename COM_Likelihood_Code-v3.0_R3.10.tar.gz
[clik] Installing from directory /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cosmo_codes/code/planck/code/plc_3.0/plc-3.1
[clik] Configuring... (and maybe installing dependencies...)
[clik] Compiling...
[clik] Finished!
[install] Successfully installed! Let's check it...
Traceback (most recent call last):
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/install.py", line 241, in install
    **kwargs_is_installed)
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 163, in is_installed
    reload=reload))
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 310, in is_installed_clik
    reload=reload, logger=get_logger("clik"), not_installed_level="debug"))
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 297, in load_clik
    clik = load_external_module(*args, **kwargs)
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/component.py", line 775, in load_external_module
    module = _bare_load_external_module(not_installed_level="debug", **load_kwargs)
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/component.py", line 701, in _bare_load_external_module
    import_path = get_import_path(path)
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 285, in get_clik_import_path
    f"Installed version of the Plack likelihood code 'clik' ({installed_version})"
cobaya.tools.VersionCheckError: Installed version of the Plack likelihood code 'clik' (packages/cosmo_codes/code/planck/code/plc_3.0/plc) older than minimum required one (3.1).
[install] *ERROR* Installation apparently worked, but the subsequent installation test failed! This does not always mean that there was an actual error, and is sometimes fixed simply by running the installer again. If not, look closely at the error messages above, or re-run with --debug for more more verbose output. If you are unable to fix the issues above, try installing the packages required by this component manually.

================================================================================


================================================================================
* Summary * 
================================================================================

[install] *ERROR* The installation (or installation test) of some component(s) has failed: 
 - likelihood:planck_2018_lowl.TT
Check output of the installer of each component above for precise error info.

[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/prm/anaconda3/envs/cobaya/bin/cobaya-install", line 8, in <module>
    sys.exit(install_script())
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/install.py", line 549, in install_script
    "no_set_global", "skip", "skip_global", "debug", "upgrade"]})
  File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/install.py", line 278, in install
    bullet + bullet.join(failed_components))
cobaya.log.LoggedError: The installation (or installation test) of some component(s) has failed: 
 - likelihood:planck_2018_lowl.TT
Check output of the installer of each component above for precise error info.

-------------------------------------------------------------

```

When I check the `readme.md` file in the planck folder, it says that clik version is 3.1. What can be done to fix this error message?

**Comment by cmbant** [comment]
I would guess you have two click installs one in home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cosmo_code and one in a local path?
________________________________
From: Pedro Riba Mello ***@***.***>
Sent: Tuesday, August 16, 2022 6:14:16 PM
To: CobayaSampler/cobaya ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CobayaSampler/cobaya] Error message while installing planck_2018_lowl.TT likelihood (Issue #255)


Hello,
I'm trying to install cobaya likelihoods on my OS, ubuntu 20.04, by running the command cobaya-install cosmo -p /path/to/packages, but it seems that it's unable to properly install the planck_2018_lowl.TT likelihood. The following error message keeps appearing:

'
likelihood:planck_2018_lowl.TT

[install] Checking if dependencies have already been installed...
[install] Check found no existing installation
[install] (If you expected this to be already installed, re-run cobaya-install with --debug to get more verbose output.)
[install] Installing...
[planck_2018_lowl.TT] Installing the clik code.
[clik] Installing pre-requisites...
Requirement already satisfied: cython in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (0.29.32)
Requirement already satisfied: astropy in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (4.3.1)
Requirement already satisfied: importlib-metadata in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from astropy) (4.12.0)
Requirement already satisfied: numpy>=1.17 in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from astropy) (1.21.6)
Requirement already satisfied: pyerfa>=1.7.3 in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from astropy) (2.0.0.1)
Requirement already satisfied: zipp>=0.5 in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from importlib-metadata->astropy) (3.8.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages (from importlib-metadata->astropy) (4.3.0)
[clik] Downloading...
2.26MiB [00:12, 187kiB/s]
[clik] Downloaded filename COM_Likelihood_Code-v3.0_R3.10.tar.gz
[clik] Installing from directory /home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cosmo_codes/code/planck/code/plc_3.0/plc-3.1
[clik] Configuring... (and maybe installing dependencies...)
[clik] Compiling...
[clik] Finished!
[install] Successfully installed! Let's check it...
Traceback (most recent call last):
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/install.py", line 241, in install
**kwargs_is_installed)
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 163, in is_installed
reload=reload))
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 310, in is_installed_clik
reload=reload, logger=get_logger("clik"), not_installed_level="debug"))
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 297, in load_clik
clik = load_external_module(*args, **kwargs)
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/component.py", line 775, in load_external_module
module = _bare_load_external_module(not_installed_level="debug", **load_kwargs)
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/component.py", line 701, in _bare_load_external_module
import_path = get_import_path(path)
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 285, in get_clik_import_path
f"Installed version of the Plack likelihood code 'clik' ({installed_version})"
cobaya.tools.VersionCheckError: Installed version of the Plack likelihood code 'clik' (packages/cosmo_codes/code/planck/code/plc_3.0/plc) older than minimum required one (3.1).
[install] ERROR Installation apparently worked, but the subsequent installation test failed! This does not always mean that there was an actual error, and is sometimes fixed simply by running the installer again. If not, look closely at the error messages above, or re-run with --debug for more more verbose output. If you are unable to fix the issues above, try installing the packages required by this component manually.

================================================================================

================================================================================

  *   Summary *
================================================================================

[install] ERROR The installation (or installation test) of some component(s) has failed:

  *   likelihood:planck_2018_lowl.TT
Check output of the installer of each component above for precise error info.

[exception handler] ---------------------------------------

Traceback (most recent call last):
File "/home/prm/anaconda3/envs/cobaya/bin/cobaya-install", line 8, in
sys.exit(install_script())
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/install.py", line 549, in install_script
"no_set_global", "skip", "skip_global", "debug", "upgrade"]})
File "/home/prm/anaconda3/envs/cobaya/lib/python3.7/site-packages/cobaya/install.py", line 278, in install
bullet + bullet.join(failed_components))
cobaya.log.LoggedError: The installation (or installation test) of some component(s) has failed:

  *   likelihood:planck_2018_lowl.TT
Check output of the installer of each component above for precise error info.

________________________________

'

When I check the 'readme.md' file in the planck folder, it says that clik version is 3.1. What can be done to fix this error message?

**Comment by pribamello** [comment]
I don't think this is the case. I created a completely new environment for this installation and tried installing the packages in cosmo_code which is in my python path.

**Comment by pribamello** [comment]
even after removing all planck folders in my os, the the same error still appears during the installation

**Comment by cmbant** [comment]
You'll have to debug where it's loading the module from, e.g. check i's __file__ after loading and see why the version check is failing.

**Comment by earosenberg** [comment]
I had the same problem and the issue seems to be in the function `get_clik_import_path` in `likelihoods/base_classes/planck_clik.py`, line 282:
` installed_version = version.parse(clik_src_path.rstrip(os.sep).split("-")[1])`
 This splits the file path for the installation folder by dashes, and so fails if there is a dash in your file path. 
In this case the path has been split into `["/home/prm/anaconda3/envs/cobaya/lib/python3.7/site", "packages/cosmo_codes/code/planck/code/plc_3.0/plc", "3.1"]` and the second list entry is being interpreted as the version number rather than the last entry (3.1). A quick (but possibly not robust) fix is to switch the [1] for a [-1] so it takes the last entry of the list.

**Comment by cmbant** [comment]
Sounds like a good idea, thanks! 
https://github.com/CobayaSampler/cobaya/commit/a6a3fe43b9a5a9fdb4863104626bde1627dbd79f

**Comment by pribamello** [comment]
I think that should fix it! Thanks!
