### ISSUE TITLE
Problem with importing cobaya

### ISSUE THREAD

**Issue by Carlos-Robel** [CobayaSampler/cobaya#262]
So, I install cobaya and make sure that this was installed in the correct place. I use Jupytwr Notebook, Spyder and Google Colab, but in any of these, when I import cobaya there appears: ModuleNotFoundError: No module named 'cobaya'.

I don't know what went wrong with the installation. I unistall and install again cobaya like 3 times and the same error occurs everytime. 3 months ago I didn't hava this problem.

**Comment by cmbant** [comment]
This sounds like a general environment issue, not specific to cobaya. Likely the environment you are installing into is not the one you are running (or the installation fails for some reason).
