### ISSUE TITLE
Comparison CLASS/CAMB

### ISSUE THREAD

**Issue by mtristram** [CobayaSampler/cobaya#274]
By default the non-linear method for CLASS is set to "hmcode" whereas the default for CAMB is "halofit".

For a fair comparison, this line should be changed to "halofit":
https://github.com/CobayaSampler/cobaya/blob/5b102d52a31dd5f668992b30b6fd4891d91dcee0/cobaya/theories/classy/classy.py#L208

**Comment by cmbant** [comment]
CAMB's default is halofit_default = halofit_mead2020, which is HMCode?

**Comment by mtristram** [comment]
Is it the same version used in CLASS when setting nonlinear to "hmcode" ?
It seems I can find a significant difference in the time execution between the two solvers which is resolved by switching CLASS to "halofit".

**Comment by cmbant** [comment]
I don't know what class is doing.
