### ISSUE TITLE
Potential issue with matter power spectrum

### ISSUE THREAD

**Issue by NaregM** [CobayaSampler/cobaya#29]
Hi,
Thanks for having the code public!
I am trying to get the matter power spectrum to use in my likelihood and as a first step (new user!) I am trying to do it in somewhat of a similar fashion to one of the examples that you have provided:

> fiducial_params = {'ombh2': 0.022, 'omch2': 0.12, 'H0': 68, 'tau': 0.07, 
>                               'As': 2.2e-9, 'ns': 0.96,
>                               'mnu': 0.06, 'nnu': 3.046, 'num_massive_neutrinos': 1}
> 
> modules_path = my_path
> 
> info_fiducial = {'params': fiducial_params,
>                 'likelihood': {'one': None},
>                 'theory': {'camb': None},
>                 'modules': modules_path}
> 
> model_fiducial = get_model(info_fiducial)
> 
> model_fiducial.likelihood.theory.needs(Pk_interpolator = {'k_max' : 3, 'z' : 0.2})
> 
> 
> model_fiducial.logposterior({})
> model_fiducial.likelihood.theory.get_Pk_interpolator()

This results in the following error:

`error: (mx>kx) failed for hidden mx: regrid_smth:mx=1`

 I would appreciate it if you take a look at it. Thank you so much.

**Comment by JesusTorrado** [comment]
Hi @NaregM,

Thanks for the clear bug report! And sorry for the delay: I've been quite busy!

It appears that you need to request at least 4 z's (the spline used internally is cubic): https://stackoverflow.com/questions/30081779/scipy-interpolate-rectbivariatespline-constructor-returns-an-error

This should work for now (though will be slower than it could). I am going to close the issue and write a pull request for CAMB to adjust the degree of the polynomial with the number of points, such that you can feed any number of z's in the future.

Cheers!

**Comment by JesusTorrado** [comment]
This is now https://github.com/cmbant/CAMB/pull/43 in CAMB.

If it gets merged, you just need to substitute your CAMB by the last one in `master` and you should be able to run your code as is.

**Comment by NaregM** [comment]
Thank you! 4 points does work.
