### ISSUE TITLE
Formatter of progress file does not work anymore with pandas 2.X series

### ISSUE THREAD

**Issue by xgarrido** [CobayaSampler/cobaya#290]
With the recent update of `pandas` to version `2.0.0` (https://github.com/pandas-dev/pandas/releases/tag/v2.0.0) I get an error when writing the progress file in mcmc sampler. When formatting the column of the number of samples to be integer (https://github.com/CobayaSampler/cobaya/blob/master/cobaya/samplers/mcmc/mcmc.py#L850), now `pandas` returns a `ValueError` exception 

```python
ValueError: Unknown format code 'd' for object of type 'float'
```

which is actually right since the number of samples returns by this line https://github.com/CobayaSampler/cobaya/blob/master/cobaya/samplers/mcmc/mcmc.py#L645 and sum up by this line https://github.com/CobayaSampler/cobaya/blob/master/cobaya/samplers/mcmc/mcmc.py#L671 is a float value. 

I guess previous versions of `pandas` was able to deal with this kind of incompatibilities. A basic fix will be to change the `d` to `f` format type 
```python
fmts = {"N": "{:9f}".format}
```
which is also backward compatible

**Comment by cmbant** [comment]
Thanks, tests passing again now https://github.com/CobayaSampler/cobaya/commit/83ca209ea0048a3da0ae65f0e74c59f64b53165a
