### ISSUE TITLE
Possible wrong units for classy Cell "tp"

### ISSUE THREAD

**Issue by carlosggarcia** [CobayaSampler/cobaya#292]
I was checking the classy implementation for another project I am working on and I have noticed that the Cell "tp" is multiplied by `(T_CMB * 1e6)**2` instead of `(T_CMB * 1e6)`. This is the line: https://github.com/CobayaSampler/cobaya/blob/2387e32ed32d6c7162440305751ee6075427c4e3/cobaya/theories/classy/classy.py#L632

For comparison, this is the MontePython implementation: https://github.com/brinckmann/montepython_public/blob/4f010ad7ede7306ada811de80cad8369dbd6338f/montepython/likelihood_class.py#L201

**Comment by JesusTorrado** [comment]
It should be fixed in https://github.com/CobayaSampler/cobaya/pull/313. @carlosggarcia you can test it now using that branch, or wait until it gets merged (very soon).

**Comment by JesusTorrado** [comment]
It's in `master` now. Closing.
