### ISSUE TITLE
Inconsistent Temperature error when trying to restart a MCMC run

### ISSUE THREAD

**Issue by louisl3grand** [CobayaSampler/cobaya#304]
Hi, 

I am having an isssue when trying to resume a MCMC run with Cobaya. When it loads the previous samples, there is an error message telling me `[0 : samplecollection] *ERROR* The sample seems to have an inconsistent temperature.` , and then the process is stopped. 

I do not understand very well what is the temperature in practice, and why it prevents cobaya from running more MCMC?

Also it could be that this inconsistent temperature comes from the first rows of the chains, that we could choose to discard at loading?
When cobaya tries to resume it prints `[0 : samplecollection] Skipping 0 rows`
So maybe there could be a way to discard the first rows when loading the samples to resume a run, and avoid the error about the temperature?

I don't know if that make sense.

Bests, 
Louis

**Comment by cmbant** [comment]
Could you attach files, or try looking at the values in collection.compute_temperature that are raising the error? (maybe allclose is too stringent after chains have been loaded from files stored with limited precision, could try changing the optional precision arguments?)

**Comment by louisl3grand** [comment]
Hi Antony,

It seems that the temperature is around 1 \pm 5e-4 for some of the chains, I am sending the files attached. 

I see that the stored values of logpost, loglike and logprior have an 8 digit precision. 
The precision on temperature (when it is equal to 1 as in my case) is 
d temp = 3*precision / logpost 
So that makes the precision on the temperature dependent on the value of logpost, which is probably not a safe check.
For instance for some of my points the logpost = 1e-5, which gives d temp = 1e-3 
If I put np.allclose(temp, temp[0], rtol=1e-3) [here](https://github.com/CobayaSampler/cobaya/blob/4a52113b1a3084f8f35a3945931df1fd2a221a5f/cobaya/collection.py#L103C3-L103C3), then the test is passed. 
But maybe it would be safer to compare not the ratio but the sum (logprior + loglike - logpost), so that the precision should always be of 3e-8 ?

[03_param_qe_tt_n32_tot_desi_cmb.zip](https://github.com/CobayaSampler/cobaya/files/12184534/03_param_qe_tt_n32_tot_desi_cmb.zip)

**Comment by cmbant** [comment]
I've just relaxed the test precision for now (https://github.com/CobayaSampler/cobaya/commit/4d7cecfdf3d274e0e60871dab8fb2e2cb3b8ed5e). Let me know if any of the other tests have issues. When he's back from holidays @JesusTorrado should probably also check over precision of these tests in more detail.

**Comment by louisl3grand** [comment]
Thanks, it all works fine for me with this lower precision, other tests are fine.
