### ISSUE TITLE
More complete documentation on subclassing Likelihood

### ISSUE THREAD

**Issue by timothydmorton** [CobayaSampler/cobaya#31]
As a new user, I have a suggestion for a bit more clarity in the documentation on how to define a new custom cosmological likelihood.  I am able to follow and model the ["Creating your own cosmological likelihood"](https://cobaya.readthedocs.io/en/latest/cosmo_external_likelihood.html) example, but it's still not clear to me how to do the same by subclassing `Likelihood`.  I think it would be great if that page also explained what the equivalent implementation of `my_like` as a class would look like, as a minimal example.

**Comment by JesusTorrado** [comment]
Good point! It's been in my to-do list for a while to write more examples, at least one including defining the likelihood as a class. I've had some boilerplate code for a while, but not much time.

I am not sure though that instantiating one of cobaya's internal classes would be a good idea anyway: I'd like users to be able to write their own generic classes that they can use outside cobaya (cobaya would then use its internal one to wrap it).

I'll keep you posted here about progress on this.

BTW, may I ask you where/how did you find our code? It'd be useful, for the purposes of finding the most efficient way of making ourselves known.

**Comment by timothydmorton** [comment]
Sounds good.  But it would be good to know how other cosmolo-developers can contribute to the internal likelihoods available in cobaya, which would require knowing how to implement the classes.

As far as how I heard about cobaya, I'm collaborating with @veragluscevic, who heard about it through her various CMB connections.  I believe she and others will be spreading the word about it at the upcoming Simons Observatory meeting next week.

**Comment by JesusTorrado** [comment]
I did play with it a little, but did not have time to add it to 2.0, sorry. Kept as a priority for 2.1.

**Comment by cmbant** [comment]
I added an outline in https://github.com/CobayaSampler/cobaya/pull/53

**Comment by cmbant** [comment]
devel branch does not how docs for making likelihood and theory classes
