### ISSUE TITLE
__main__.py

### ISSUE THREAD

**Issue by cmbant** [CobayaSampler/cobaya#328]
Do we need this? Odd duplication of stuff in toml (and out of date, missing e.g. running_jobs)

**Comment by cmbant** [comment]
I have updated it to pull from pip-installed metadata (does require pip installation); https://github.com/CobayaSampler/cobaya/pull/326

**Comment by JesusTorrado** [comment]
Fixed by https://github.com/CobayaSampler/cobaya/commit/37d957b208b5e0e9bbc8ff722ef325a2e5fdb2be
