### ISSUE TITLE
Access to zstar from theories and likelihoods

### ISSUE THREAD

**Issue by itrharrison** [CobayaSampler/cobaya#336]
When doing e.g. Limber calculations for CMB lensing in soliket theories and likelihoods, it would be useful to have access to zstar at the current cosmology. Is it possible to add this to what the Boltzmann codes can provide?

**Comment by cmbant** [comment]
It should already be possible to get zstar (return "'zstar" from get_requirements())

**Comment by cmbant** [comment]
Closing as assuming OK
