### ISSUE TITLE
Cobaya icon in dark mode

### ISSUE THREAD

**Issue by cmbant** [CobayaSampler/cobaya#338]
almost invisible in dark mode

**Comment by cmbant** [comment]
super trivial... 

![image](https://github.com/CobayaSampler/cobaya/assets/3958819/b09fc59b-925f-467a-950c-841e15084a9f)

**Comment by JesusTorrado** [comment]
Just uploaded new image with clear drop shadow. Does not need a commit. Hope it helps!

**Comment by cmbant** [comment]
slightly
![image](https://github.com/CobayaSampler/cobaya/assets/3958819/4b787e9f-f81c-471f-bd43-2564adb04861)
