### ISSUE TITLE
Error installing likelihood data

### ISSUE THREAD

**Issue by jpbrandtu** [CobayaSampler/cobaya#340]
Hi,

When running `cobaya-install planck_2018_highl_plik.TTTEEE` I get the following error:

```
[install] Installing external packages at '/jpbrandt/packages'
[install] The installation path has been written into the global config file: /jpbrandt/.config/cobaya/config.yaml

================================================================================
planck_2018_highl_plik.TTTEEE
================================================================================

[install] Checking if dependencies have already been installed...
[install] Check found no existing installation
[install] (If you expected this to be already installed, re-run `cobaya-install` with --debug to get more verbose output.)
[install] Installing...
[clik] `clik` module loaded successfully from /jpbrandt/packages/code/planck/clik-main/lib/python/site-packages/clik
[planck_2018_highl_plik.TTTEEE] Downloading the likelihood data.
[planck_2018_highl_plik.TTTEEE] *ERROR* Error downloading https://pla.esac.esa.int/pla-sl/data-action?COSMOLOGY.COSMOLOGY_OID=151902' to folder '/tmp/tmpsmnm7a8f': HTTPSConnectionPool(host='pla.esac.esa.int', port=443): Max retries exceeded with url: /pla-sl/data-action?COSMOLOGY.COSMOLOGY_OID=151902 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbf2de66430>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[planck_2018_highl_plik.TTTEEE] *ERROR* Not possible to download this likelihood.
[install] *ERROR* Installation failed! Look at the error messages above. Solve them and try again, or, if you are unable to solve them, install the packages required by this component manually.

================================================================================
* Summary * 
================================================================================

[install] *ERROR* The installation (or installation test) of some component(s) has failed: 
 - likelihood:planck_2018_highl_plik.TTTEEE
Check output of the installer of each component above for precise error info.

[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/jpbrandt/.conda/envs/PBH/bin/cobaya-install", line 8, in <module>
    sys.exit(install_script())
  File "/jpbrandt/.conda/envs/PBH/lib/python3.9/site-packages/cobaya/install.py", line 642, in install_script
    install(*infos, path=getattr(arguments, packages_path_arg), logger=logger,
  File "/jpbrandt/.conda/envs/PBH/lib/python3.9/site-packages/cobaya/install.py", line 360, in install
    raise LoggedError(
cobaya.log.LoggedError: The installation (or installation test) of some component(s) has failed: 
 - likelihood:planck_2018_highl_plik.TTTEEE
Check output of the installer of each component above for precise error info.

-------------------------------------------------------------
```

**Comment by cmbant** [comment]
Just a temporary problem with the PLA site? If you can't download the data files manually, this is not a Cobaya bug.

**Comment by rodrigovonmarttens** [comment]
Is this the same case? It looks different... 

------------------------------------------------------------------------------------------------------------------------------------------------------------
================================================================================
likelihood:planck_2018_highl_plik.TTTEEE
================================================================================

[install] Checking if dependencies have already been installed...
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/rodrigovonmarttens/anaconda3/bin/cobaya-install", line 8, in <module>
    sys.exit(install_script())
             ^^^^^^^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/cobaya/install.py", line 637, in install_script
    install(*infos, path=getattr(arguments, packages_path_arg), logger=logger,
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/cobaya/install.py", line 262, in install
    has_been_installed = is_installed(
                         ^^^^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 162, in is_installed
    result &= bool(is_installed_clik(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 311, in is_installed_clik
    return bool(load_clik(
                ^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 300, in load_clik
    clik = load_external_module(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/cobaya/component.py", line 818, in load_external_module
    module = _bare_load_external_module(not_installed_level="debug", **load_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/cobaya/component.py", line 741, in _bare_load_external_module
    import_path = get_import_path(path)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/cobaya/likelihoods/base_classes/planck_clik.py", line 283, in get_clik_import_path
    installed_version = version.parse(f.readline().split("_")[-1].split('-')[0])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/home/rodrigovonmarttens/anaconda3/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'net'
-------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by cmbant** [comment]
Looks difererent to me, in the "svnversion" file of the clik download (https://codeload.github.com/benabed/clik/zip/refs/heads/main) I see "clik_16.0b1-2-g63c889f3aa9c", not sure where the "net" is coming from?

**Comment by rodrigovonmarttens** [comment]
I don´t know too... I got this error message when I tried to install PlanckTTTEEE via cobaya-install. I'll also try to install Planck likelihood without cobaya-install...

**Comment by cmbant** [comment]
What's in your svnversion file?

**Comment by rodrigovonmarttens** [comment]
Sorry but how can I see that? I can´t find where cobaya downloaded click.

**Comment by cmbant** [comment]
In latest master I've tried to change the way it gets the version so hopefully more reliable
https://github.com/CobayaSampler/cobaya/compare/v3.5.4...master
