### ISSUE TITLE
Backward Compatibility with python 3.9 

### ISSUE THREAD

**Issue by Kushallodha** [CobayaSampler/cobaya#345]
After [#326](https://github.com/CobayaSampler/cobaya/pull/326), Cobaya has become incompatible with Python<=3.9.  I believe one of the reasons is due to the use of 

```python
commands = {}
for script in metadata.entry_points().select(group='console_scripts'):
        if script.name.startswith('cobaya-'):
            commands[script.name] = script.value
    help_msg = ("Add a one of the following commands and its arguments "
                "(`<command> -h` for help): %r" % list(commands))`
```
in `cobaya/__main__.py`.
The `metadata.entry_points()` didn't have a select method in < v3.10. I am aware Python 3.9's full support ended in 2022, but it would be great if we could somehow maintain backward compatibility till the end of its lifetime (2025). I am unsure if this has already been discussed elsewhere or if the authors have decided to end Cobaya support for Python <=3.9.

**Comment by cmbant** [comment]
Thanks for the report. But you shouldn't need to use __main__ - e.g. cobaya-run etc can be run directly (personally I never use the __main__ version).

**Comment by Kushallodha** [comment]
I've been using **main** due to past issues with occasionally environmental variables and paths not being properly exported in job scripts. If directly calling console scripts resolves this, then it's not a significant concern.

**Comment by Kushallodha** [comment]
Is there a way to use debugging tools like `pdb` with console commands directly?

**Comment by cmbant** [comment]
I don't know, I always debug in pycharm.
