### ISSUE TITLE
Script invocation is broken on Python 3.9

### ISSUE THREAD

**Issue by HTJense** [CobayaSampler/cobaya#348]
It appears that `importlib.metadata.entry_points()` changed its return type from a dict to an object in python 3.10, and thus script invocation errors at [line 12 of __main__.py](https://github.com/CobayaSampler/cobaya/blob/master/cobaya/__main__.py#L12) when using Python versions prior to 3.10. See also the "compatibility note" at the bottom of [this](https://docs.python.org/3/library/importlib.metadata.html#entry-points) section.

Either versions 3.9 and before should be dropped (they don't seem to be flagged as incompatible in pyproject.toml), or a backwards-compatible fix should be considered (EOL for 3.9 won't be in another year and a half).

**Comment by HTJense** [comment]
(I should clarify that this is only for the development branch, not the latest release).

**Comment by cmbant** [comment]
c.f. https://github.com/CobayaSampler/cobaya/issues/345

**Comment by cmbant** [comment]
and https://github.com/CobayaSampler/cobaya/issues/328

**Comment by JesusTorrado** [comment]
Restored backwards compatibility by https://github.com/CobayaSampler/cobaya/commit/12d26c627465be925c2863ed6ba6054e2a458191
