### ISSUE TITLE
Interpolation error creating a delta chi2 = 20 on DESI likelihood

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#352]
Hi @cmbant @JesusTorrado 

In both CAMB and CLASS (older version of Cobaya - so I have not tested if this problem is absent on new versions). I was getting chi2 ~40 for DESI and horrible predictions on bin z = 1.4 

Then I made this change (picture attached) 

<img width="1217" alt="Screenshot 2024-04-08 at 1 58 25 AM" src="https://github.com/CobayaSampler/cobaya/assets/3210728/4ae459c9-817d-4dc5-a741-96c9b1ce3019">

and chi2 drop to 20. 

With the fix (random cosmology - see the z=1.49 prediction and DESI chi2):

<img width="696" alt="Screenshot 2024-04-08 at 2 02 06 AM" src="https://github.com/CobayaSampler/cobaya/assets/3210728/c4e4b1f8-ba02-49ba-b73e-75a749189d24">

Without the fix 

<img width="679" alt="Screenshot 2024-04-08 at 2 03 54 AM" src="https://github.com/CobayaSampler/cobaya/assets/3210728/94473b3d-50f9-44ca-a351-4b0da81ebd23">

**Comment by cmbant** [comment]
Perhaps this was fixed with https://github.com/CobayaSampler/cobaya/pull/344 - can you check on latest master?

The DESI Y1 likelihood in the current master (from DESI team) returns a chi2 of about 21 on the test point.

**Comment by vivianmiranda** [comment]
I will check that.


On another note - the cover matrix of Pantheon+ (and dv) looks like a javascript code

https://github.com/CobayaSampler/sn_data/blob/master/PantheonPlus/Pantheon%2BSH0ES_STAT%2BSYS.cov

And I am getting reading errors. Is that the correct file?

**Comment by vivianmiranda** [comment]
Also DES-Y5 is missing (STAT+SYS.txt) 

https://github.com/CobayaSampler/sn_data/tree/master/DESY5

**Comment by cmbant** [comment]
No it’s not, should be same as

https://github.com/PantheonPlusSH0ES/DataRelease/blob/main/Pantheon%2B_Data/4_DISTANCES_AND_COVAR/Pantheon%2BSH0ES_STAT%2BSYS.cov

Antony

**Comment by cmbant** [comment]
PantheonPlus should be fixed now. (I don't have a test value to add a unit test)

**Comment by cmbant** [comment]
Also DES Y5 (thanks, looks like an inconsistency in the names in the original repo)

**Comment by cmbant** [comment]
Is DESI OK for you now on master, can we close?
