### ISSUE TITLE
Installing DESI data: could not be found error

### ISSUE THREAD

**Issue by ark93-cosmo** [CobayaSampler/cobaya#355]
Hi,
I'm trying to install the DESI data using:
`cobaya-install MyFile.yaml`
after upgrading COBAYA to v3.5. In my yaml file, I tried:
bao.desi_2024_bao_bgs_z1: null
or
desi_2024_bao_bgs_z1: null
or
bao.desi_y1: null
but I keep getting a ``could not be found'' error. Also, the alternative suggestions do not include anything related to DESI.
Is this cosmo package installation method not updated to work for DESI data?
Otherwise, how could I install the required files?
Thanks!

**Comment by cmbant** [comment]
Make sure you installed latest master branch.

**Comment by cmbant** [comment]
I don't think so, think that gets from pypy

**Comment by ark93-cosmo** [comment]
I see, so my only option is to git clone the master branch.
Thanks Antony!
