### ISSUE TITLE
bao.generic likelihood not working for the distances of type Dv_over_rs

### ISSUE THREAD

**Issue by prakharbansal16** [CobayaSampler/cobaya#363]
I'm trying to use the DESI 2024 data files using the bao.generic likelihood but I'm getting an error 
"angular_diameter_distance not computed for all z requested"

Looks like the problem is with the datapoint Dv_over_rs. I also tried with the file "test_bao_mixed_observables_mean.txt" in the bao datasets and am getting the same error.

**Comment by cmbant** [comment]
What's the difference with the test_cosmo_bao:test_generic_mixed_camb test, which I think passes?

**Comment by prakharbansal16** [comment]
I'm sorry I didn't quite get what you said. So is it like these two are datasets which I should try? I can't find them though in the bao datasets directory.

**Comment by prakharbansal16** [comment]
I was using the an older version (3.3.2). I had installed it using the command on the website "python -m pip install cobaya --upgrade". I manually installed the latest version using "pip install cobaya==3.5.1". But when I import cobaya in a script I get an error 

"ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject"

**Comment by JesusTorrado** [comment]
A simple web search of the error message suggests reinstalling numpy: `pip uninstall numpy` and `pip install numpy`.

**Comment by prakharbansal16** [comment]
Thanks, it was indeed the problem.
