### ISSUE TITLE
NPIPE likelihood

### ISSUE THREAD

**Issue by GowriNair38** [CobayaSampler/cobaya#366]
Hi
Can anyone tell me the code for the likelihood code that I will have to run to use the NPIPE data?

Thanks!

**Comment by cmbant** [comment]
The CamSpec CMB power spectra one is included as planck_NPIPE_highl_CamSpec. (please ask questions on CosmoCoffee, this is intended for bug reports/feature requests)

**Comment by GowriNair38** [comment]
Alright, thanks!
