### ISSUE TITLE
Cobaya 3.5.1 and ACT

### ISSUE THREAD

**Issue by JeremiasBezerra** [CobayaSampler/cobaya#367]
I was using Cobaya 3.3.1 with ACT DR4 likelihood. So I decided to update Cobaya to 3.5.1. to use DESI data

And using the same .yaml and I get the error:

![image](https://github.com/user-attachments/assets/e43dc842-84da-4f79-a00b-23000b7b3965)

If I go back to the old version (3.3.1) and consequently without using DESI data, the code works normally. Would you have any idea why this is happening?

**Comment by cmbant** [comment]
I think theory was removed after being deprecated. Replace with "provider".

**Comment by cmbant** [comment]
Added issue here https://github.com/ACTCollaboration/pyactlike/issues/21
