### ISSUE TITLE
Attribute error with cobaya commands

### ISSUE THREAD

**Issue by prakharbansal16** [CobayaSampler/cobaya#381]
Hi, I'm trying to setup Cobaya on my new device. I checked the installation and am able to import cobra. But whenever I try to run a cobaya command for eg. "python3 -m cobaya run" I get an error message 

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/prakharbansal/Library/Python/3.9/lib/python/site-packages/cobaya/__main__.py", line 47, in <module>
    run_command()
  File "/Users/prakharbansal/Library/Python/3.9/lib/python/site-packages/cobaya/__main__.py", line 15, in run_command
    metadata.entry_points().select(group="console_scripts")
AttributeError: 'dict' object has no attribute 'select'
```

**Comment by cmbant** [comment]
Are you sure you're using the latest Cobaya version? (you can normally just use "cobaya-run" instead anyway)

**Comment by prakharbansal16** [comment]
Yeah, I tried that but I think cobaya is not added to path and I couldn't find the instructions to add it to the path on MAC

**Comment by cmbant** [comment]
Do you have 3.5.4? (and installed in current env)

**Comment by cmbant** [comment]
(the command is "cobaya-run" not "cobaya")

**Comment by prakharbansal16** [comment]
Yes, I have cobaya 3.5.4 installed and I was trying the command cobaya-run itself

**Comment by cmbant** [comment]
Check what is in your Users/prakharbansal/Library/Python/3.9/lib/python/site-packages/cobaya/__main__.py script. There should be a `sys.version_info > (3, 9)`. which should not apply if you are running from 3.9.
If "cobaya-run" is not on path, it may indicate you don't have the correct env activated (and hence maybe running an old version).

**Comment by prakharbansal16** [comment]
Yes the line `sys.version_info > (3, 9)`  is there. I'm using the python version 3.9.6, could that be the reason?

**Comment by cmbant** [comment]
Ah maybe, does it work if you change to >= (3, 10)?

**Comment by cmbant** [comment]
Closing for now assuming https://github.com/CobayaSampler/cobaya/commit/d14d6c3984b315a09ff8e2ef8e011593a63185d8 fixes it, thanks.
