### ISSUE TITLE
Constraints on derived parameters

### ISSUE THREAD

**Issue by krtktwri** [CobayaSampler/cobaya#386]
I'm relatively new to cobaya. So, I suspect this might be rather trivial to some. I wanted to put constraints on my derived parameters and it took me quite some time (and wasted computing resources) to realize that derived parameters cannot be constrained directly from the YAML file and that, effectively, the only way to excise a region from the prior space is to define a custom constraint likelihood function. 

This really adds friction to workflows which, otherwise, simply require only interfacing with installed likelihoods. I'm wondering if there is a way to streamline inclusion of constraints on derived parameters within cobaya workflow (when using from terminal).

I'm thinking essentially of a module that can generate a python file like the following given a lambda definition of the constraint. In the following example, I'm sampling w and wa but applying an additional constrain such that w + wa > -1 (to stay out of the phantom regime)

```
import numpy as np

def constraint(
        w=-1.0,  # default value for w
        wa=0.0,  # default value for wa
        _self=None):

    # Check the constraint
    if w + wa < -1:
        return -np.inf, {}  # Constraint violated

    # Placeholder for additional likelihood computation
    logp = 0  # Replace this with actual likelihood calculation if necessary

    # Example of a derived parameter you might want to return
    derived = {'w_plus_wa': w + wa}

    return logp, derived 
```

**Comment by cmbant** [comment]
You can put lambdas in the yaml, see 
https://cobaya.readthedocs.io/en/latest/params_prior.html#priors-on-theory-derived-parameters
Personally I'd never normally do things only via the terminal, so I think the suggest is a bit niche and hard to generalize for a general cobaya change.
