### ISSUE TITLE
Error in DES Likelihood with CLASS

### ISSUE THREAD

**Issue by jcolinhill** [CobayaSampler/cobaya#46]
When running the DES likelihood out of the box with CLASS, I get the following error message:

[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/mnt/home/chill/.local/lib/python3.7/site-packages/cobaya/theories/classy/classy.py", line 352, in compute
    i_state = next(i for i in range(self.n_states)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/chill/.local/bin/cobaya-run", line 10, in <module>
    sys.exit(run_script())
  File "/mnt/home/chill/.local/lib/python3.7/site-packages/cobaya/run.py", line 154, in run_script
    run(info)
  File "/mnt/home/chill/.local/lib/python3.7/site-packages/cobaya/run.py", line 87, in run
    sampler.run()
  File "/mnt/home/chill/.local/lib/python3.7/site-packages/cobaya/samplers/evaluate/evaluate.py", line 65, in run
    self.logposterior = self.model.logposterior(reference_point)
  File "/mnt/home/chill/.local/lib/python3.7/site-packages/cobaya/model.py", line 280, in logposterior
    make_finite=make_finite, cached=cached, _no_check=True)
  File "/mnt/home/chill/.local/lib/python3.7/site-packages/cobaya/model.py", line 186, in loglikes
    _derived=_derived, cached=cached)
  File "/mnt/home/chill/.local/lib/python3.7/site-packages/cobaya/likelihood.py", line 356, in logps
    **theory_params_dict)
  File "/mnt/home/chill/.local/lib/python3.7/site-packages/cobaya/theories/classy/classy.py", line 401, in compute
    *self.collectors[product].args, **self.collectors[product].kwargs)
  File "classy.pyx", line 920, in classy.Class.get_pk_and_k_and_z
  File "classy.pyx", line 1155, in classy.Class.z_of_tau
classy.CosmoSevereError:

Error in Class: background_at_tau(L:122) :condition (tau > pba->tau_table[pba->bt_size-1]) is true; out of range: tau=1.417296e+04 > tau_max=1.417296e+04

-------------------------------------------------------------

After digging into this for quite awhile, my best guess for the cause of the problem is the construction of self.zs_interp and self.zs in _des_prototype.py.  The former array causes the code to try to evaluate P(k,z) down to z=0, but it seems that this causes problems by requiring evaluation beyond the lowest z at which the code has pre-evaluated P(k).  It seems this is around z=0.005, hence my guess that it's connected to self.zs, which explicitly has a hard-coded lower limit of 0.005.

However, if I try to remedy this by setting the lower limit of self.zs to 0, then the code segfaults.  For various values between 0.005 and 0, it either throws the same error as above or segfaults.  Perhaps the issues is occurring elsewhere -- any help would be greatly appreciated.

**Comment by jcolinhill** [comment]
Thanks @JesusTorrado -- sorry for not attaching the file originally, here it is-


likelihood:
  planck_2018_lowl.TT:
  planck_2018_lowl.EE:
  planck_2018_highl_plik.TTTEEE_lite:
  planck_2018_lensing.clik:
  bao.sixdf_2011_bao:
  bao.sdss_dr7_mgs:
  sn.pantheon:
  H0.riess201903:
  des_y1.joint:
modules: /mnt/home/chill/cobaya/modules
params:
  logA:
    prior:
      min: 1.61
      max: 3.91
    ref:
      dist: norm
      loc: 3.05
      scale: 0.001
    proposal: 0.001
    latex: \log(10^{10} A_\mathrm{s})
    drop: true
  A_s:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
  n_s:
    prior:
      min: 0.8
      max: 1.2
    ref:
      dist: norm
      loc: 0.965
      scale: 0.004
    proposal: 0.002
    latex: n_\mathrm{s}
  theta_s_1e2:
    prior:
      min: 0.5
      max: 10
    ref:
      dist: norm
      loc: 1.0416
      scale: 0.0004
    proposal: 0.0002
    latex: 100\theta_\mathrm{s}
    drop: true
  100*theta_s:
    value: 'lambda theta_s_1e2: theta_s_1e2'
    derived: false
  H0:
    latex: H_0
  omega_b:
    prior:
      min: 0.005
      max: 0.1
    ref:
      dist: norm
      loc: 0.0224
      scale: 0.0001
    proposal: 0.0001
    latex: \Omega_\mathrm{b} h^2
  omega_cdm:
    prior:
      min: 0.001
      max: 0.99
    ref:
      dist: norm
      loc: 0.12
      scale: 0.001
    proposal: 0.0005
    latex: \Omega_\mathrm{c} h^2
  Omega_m:
    latex: \Omega_\mathrm{m}
  omegamh2:
    derived: 'lambda Omega_m, H0: Omega_m*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  m_ncdm:
    value: 0.06
    renames: mnu
  Omega_Lambda:
    latex: \Omega_\Lambda
  YHe:
    latex: Y_\mathrm{P}
  tau_reio:
    prior:
      min: 0.01
      max: 0.8
    ref:
      dist: norm
      loc: 0.055
      scale: 0.006
    proposal: 0.003
    latex: \tau_\mathrm{reio}
  z_reio:
    latex: z_\mathrm{re}
  sigma8:
    latex: \sigma_8
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, Omega_m: sigma8*Omega_m**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, Omega_m: sigma8*Omega_m**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  A:
    derived: 'lambda A_s: 1e9*A_s'
    latex: 10^9 A_\mathrm{s}
  clamp:
    derived: 'lambda A_s, tau_reio: 1e9*A_s*np.exp(-2*tau_reio)'
    latex: 10^9 A_\mathrm{s} e^{-2\tau}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
  rs_drag:
    latex: r_\mathrm{drag}
  chi2__CMB:
    derived: 'lambda chi2__planck_2018_lowl_TT, chi2__planck_2018_lowl_EE, chi2__planck_2018_highl_plik_TTTEEE_lite,
      chi2__planck_2018_lensing_clik: sum([chi2__planck_2018_lowl_TT, chi2__planck_2018_lowl_EE,
      chi2__planck_2018_highl_plik_TTTEEE_lite, chi2__planck_2018_lensing_clik])'
    latex: \chi^2_\mathrm{CMB}
sampler:
  mcmc:
    covmat: auto
    drag: true
    proposal_scale: 1.9
theory:
  classy:
    extra_args:
      non linear: halofit
      N_ncdm: 1
      N_ur: 2.0328

output: chains/planck2018_baseLCDM_lowTT_lowEE_plikHM_TTTEEE_lite_lensing_BAO_DR7_DR12_6dF_SNPantheon_SH0ES201903_DES

**Comment by JesusTorrado** [comment]
Thanks, Colin!

I just noticed we already found this error a while ago, and a patch was written by one of the CLASS developers, which unfortunately never made it upstream. I am checking what I can do, and if it makes sense waiting for CLASS 2.8 (I've been promised an early peek into the beta, to try to iron all this out before release).

**Comment by jcolinhill** [comment]
OK, thanks!  My guess was that a small change to these lines in _des_prototype.py could fix it:
        # Fine z sampling                                                                                                                                                                                
        if self.acc > 1:
            self.zs = np.linspace(0.005, self.zmax, int(350 * self.acc))
        else:
            self.zs = self.zmid[self.zmid <= self.zmax]
        # Interpolator z sampling                                                                                                                                                                        
        assert self.zmax <= 5, "z max too large!"
        self.zs_interp = np.linspace(0, self.zmax, 100)

or possibly a small change to these lines in classy.pyx:
        # Get k and z arrays
        for index_k in xrange(self.sp.ln_k_size):
            k[index_k] = np.exp(self.sp.ln_k[index_k])
        for index_tau in xrange(self.sp.ln_tau_size):
            z[index_tau] = self.z_of_tau(np.exp(self.sp.ln_tau[index_tau]))

        # Avoid saturating the limits
        z[-1] *= (1-eps)
        z[0] *= (1+eps)
	if(z[0] < eps):
          z[0] = 0

but perhaps the needed patch is larger than this.

**Comment by borisbolliet** [comment]
This is not a cobaya issue but a class issue. 

One solution is to go to line 3252 of source/input.c in class (version 2.7) and replace:

ppr->a_ini_over_a_today_default = 1e-14;

by

ppr->a_ini_over_a_today_default = 1e-16;

**Comment by jcolinhill** [comment]
Very cool, thanks Boris!  Is there any chance that this change will cause problems elsewhere in CLASS?

**Comment by borisbolliet** [comment]
It's a possibility, nevertheless the function get_pk_and_k_z() is defined in the wrapper... so the problem may just be inherent to this function and nothing else. 

Anyway as Jesus mentioned,  there is a new class version coming up so i guess it will be fixed properly.

**Comment by JesusTorrado** [comment]
Seems to we working with CLASS 2.9.3 (updated in `devel` branch, to be released very soon).
