### ISSUE TITLE
column mismatch between cobaya output and raw_polychord_output

### ISSUE THREAD

**Issue by lukashergt** [CobayaSampler/cobaya#47]
I want to work with the raw PolyChord output, but the lack of a `.paramnames` file is a problem for me. I tried using the param names that are detected by GetDist, but I got a column mismatch, i.e. GetDist had more param names than columns in the raw PolyChord output.

When running PolyChord with Cobaya the PolyChord output is stored in the folder `raw_polychord_output` and in particular a sample file is produced `raw_polychord_output/<rootname>.txt`. With other codes (CosmoChord, MontePython) also a `.paramnames` file is produced which allows to identify the param names corresponding to columns in the sample file. Cobaya doesn't create a paramnames file instead it produces a sample file `<rootname>.1.txt`, which has a file header specifying the columns. However, this sample file has two more columns than the files in `raw_polychord_output`. 

* Which two columns are additionally stored in `<rootname>.1.txt`?
* Are those two columns appended to the end?
* How can I find out the param names corresponding to the columns in the raw PolyChord output?

**Comment by lukashergt** [comment]
I noticed that there is a line in the output that says:
```
[0 : polychord]   write_paramnames: False
```
Unfortunately, Cobaya doesn't accept `write_paramnames: true` as an option in the yaml file:
```
[input] *ERROR* 'polychord' does not recognize some options: 'write_paramnames' (did you mean 'renames'|'write_resume'|'write_dead'?). To see the allowed options, check out the documentation of this module.
```

* Would it be possible to make `write_paramnames: true` an option for the yaml file?
* Could ideally `write_paramnames: true` be the default behaviour with the `<rootname>.paramnames` file written into the `raw_polychord_output` folder?

**Comment by JesusTorrado** [comment]
Hi @lukashergt 

Sorry for the delay. I have implemented this in branch `new_speed_blocking`, which is the de-facto devel, and the one I recommend you to use right now. I hope you can still find this feature useful.
