### ISSUE TITLE
Theta_STAR

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#48]
Hi 

I am trying to do something that used to be quite simple in CosmoMC

I am sampling on omega_b, omega_c and H_0. I have to sample on those parameters for my test.

But I want to add a gaussian likelihood on theta_star (or theta_MC). So I try to add

```
def add_theory(self):
   self.theory.needs(**{
            "theta_star": None
            })
```

but it failed. I try to look for similar words but I couldn't find it. What am I missing?

PS: This would help - among other things - to implement the Planck 2015 compressed likelihood. But for DES purposes - we sample on H0

Best
Vivian

**Comment by Stefan-Heimersheim** [comment]
Hi Vivian,

this sounds like you just want to manually add a likelihood, so you have to add another likelihood to your cobaya dictionary

    sampler['likelihood'] = {
                        'theta_star_likelihood': {
                        'external': theta_star_gaussian,
                        },
                        # other likelihoods ...

with some Gaussian

    def theta_star_gaussian(theta_star):
         return scipy.stats.norm.logpdf(...)

I think there is also an even shorter way without defining the `external` function but the key is adding the Gaussian to your likelihoods.

Cheers,
Stefan

PS: Name of function and likelihood is not important, just the argument of the likelihood function has to match your parameter.

**Comment by vivianmiranda** [comment]
Thank you. 
 
Will this work even if I am not sampling on \theta? I am sampling on H0 instead and I can't change that because my work is in the context of DES. That has been my problem - how to find \theta variable when I am sampling H0.

**Comment by Stefan-Heimersheim** [comment]
Hmm, I see the problem and I can't find a solution in this case.

It should be possible to get theta (probably `100*theta_s` or `theta_s_1e2`) out of classy and use it for the likelihood. In the cobaya documentation [here](https://cobaya.readthedocs.io/en/latest/theory_class.html#usage) it says `any param that CLASS understands` but I don't know how to do that, especially because `100*theta_s` is a terrible variable name ...

**Comment by cmbant** [comment]
Does it not work by making a new likelihood as Jesus suggested in https://github.com/CobayaSampler/cobaya/issues/18? "thetastar" is a standard CAMB derived parameter so you should be able to get it from _theory (and then rescale?).

If it doesn't work a simple toy example yaml/.py to reproduce the issue might be helpful - we are working on some significant internal changes at the moment that may make more general dependencies possible and useful to have test cases.

**Comment by vivianmiranda** [comment]
@JesusTorrado @cmbant any idea on how I can do this?

**Comment by cmbant** [comment]
I haven't tried but as above but with something like this (assuming CAMB)?

```
def theta_star_gaussian(_theory={'thetastar'}):
     thetastar = _theory.get_param('thetastar')
    . ...
```

**Comment by vivianmiranda** [comment]
Thank you

like_theta: "lambda _theory={'thetastar': None}: stats.norm.logpdf(_theory.get_param('thetastar'),loc=1.04092,scale=0.0031)"  

worked. I was misspelling the thetastar variable (I was including an _ in between) before. You are all the best!
