### ISSUE TITLE
Omega_M parameterization error

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#5]
Hi 

I am being unable to work with omegam and omegab parameterization.

Here is the error (I also attached my yaml ini file)

<img width="951" alt="screen shot 2018-11-15 at 5 56 34 pm" src="https://user-images.githubusercontent.com/3210728/48591265-6cd57380-e900-11e8-80b9-d61d119e6835.png">

[test2.yaml.txt](https://github.com/CobayaSampler/cobaya/files/2587601/test2.yaml.txt)

**Comment by JesusTorrado** [comment]
Fixed in https://github.com/CobayaSampler/cobaya/commit/4e3489e19c8db9e70d564106951ed5c1acb655ec sorry!
