### ISSUE TITLE
Support for text-parameters (e.g. 'reio_parametrization')?

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [CobayaSampler/cobaya#50]
Hi,

I'm trying to run `cobaya` with different reionization histories but this requires giving `classy` strings with parameters as input like this `params['many_tanh_xe']='-2,-1,0.2'` (see simple example below).

However, I see no way to pass this to classy in cobaya. One has to write a custom likelihood function that is clear but I cannot create a model with this string as parameter because cobaya always interprets it as an external function (error depends on quoting):

    [tools] *ERROR* Failed to load external function: 'NameError("name 'reio_camb' is not defined")'
    [tools] *ERROR* The external function provided is not an actual function. Got: ''reio_camb''

Problematic cobaya exampe:

    from cobaya.model import get_model
    cosmo = {'theory': {'classy': {}}, 'likelihood': {'planck_2018_lowl.TT': None}}
    cosmo['modules'] = "/home/stefan/var/cobaya_modules/"
    cosmo['params'] = {'omega_cdm': {'prior': {'min': 0.001, 'max': 0.99}},
                       'reio_parametrization': 'reio_camb'}
    model = get_model(cosmo)

Normal cobaya example:

    from cobaya.model import get_model
    cosmo = {'theory': {'classy': {}}, 'likelihood': {'planck_2018_lowl.TT': None}}
    cosmo['modules'] = "/home/stefan/var/cobaya_modules/"
    cosmo['params'] = {'omega_cdm': {'prior': {'min': 0.001, 'max': 0.99}}}         
    model = get_model(cosmo)
    params = {'omega_cdm':0.12, 'A_planck':1}
    loglike,_ = model.loglike(params)
    print(loglike)

Working classy example:

    from classy import Class
    cosmo = Class()
    params={'output': 'tCl lCl','l_max_scalars': 2000,'lensing': 'yes'}
    params['reio_parametrization']='reio_many_tanh'
    params['many_tanh_num']='3'
    params['many_tanh_z']='3.5,6, 27.5'
    params['many_tanh_xe']='-2,-1,0.2'
    params['many_tanh_width']='0.5,0.5,3'
    cosmo.set(params)
    cosmo.compute()
    cosmo.lensed_cl(2000)

Full traceback of problematic example:

    [tools] *ERROR* Failed to load external function: 'NameError("name 'reio_camb' is not defined")'
    
    -------------------------------------------------------------
    NameError                   Traceback (most recent call last)
    ~/.local/lib/python3.7/site-packages/cobaya/tools.py in get_external_function(string_or_function, name, or_class)
        175                 sys.path.append(os.path.realpath(os.curdir))
    --> 176             function = eval(string_or_function)
        177         except Exception as e:
    
    ~/.local/lib/python3.7/site-packages/cobaya/tools.py in <module>
    
    NameError: name 'reio_camb' is not defined
    
    During handling of the above exception, another exception occurred:
    
    LoggedError                 Traceback (most recent call last)
    <ipython-input-1-8350a15f398d> in <module>
          7 cosmo['params'] = {'omega_cdm': {'prior': {'min': 0.001, 'max': 0.99}},
          8                    'reio_parametrization': 'reio_camb'}
    ----> 9 model = get_model(cosmo)
    
    ~/.local/lib/python3.7/site-packages/cobaya/model.py in get_model(info)
         60     return Model(updated_info[_params], updated_info[_likelihood],
         61                  updated_info.get(_prior), updated_info.get(_theory),
    ---> 62                  modules=info.get(_path_install), timing=updated_info.get(_timing))
         63 
         64 
    
    ~/.local/lib/python3.7/site-packages/cobaya/model.py in __init__(self, info_params, info_likelihood, info_prior, info_theory, modules, timing, allow_renames)
         86                 self._updated_info[k] = deepcopy_where_possible(v)
         87         self.parameterization = Parameterization(
    ---> 88             self._updated_info[_params], allow_renames=allow_renames)
         89         self.prior = Prior(self.parameterization, self._updated_info.get(_prior, None))
         90         self.likelihood = Likelihood(
    
    ~/.local/lib/python3.7/site-packages/cobaya/parameterization.py in __init__(self, info_params, allow_renames, ignore_unused_sampled)
        132                 else:
        133                     self._input[p] = None
    --> 134                     self._input_funcs[p] = get_external_function(info[_p_value])
        135                     self._input_args[p] = getargspec(self._input_funcs[p]).args
        136             if is_sampled_param(info):
    
    ~/.local/lib/python3.7/site-packages/cobaya/tools.py in get_external_function(string_or_function, name, or_class)
        178             raise LoggedError(
        179                 log, "Failed to load external function%s: '%r'",
    --> 180                 " '%s'" % name if name else "", e)
        181     else:
        182         function = string_or_function
    
    LoggedError: Failed to load external function: 'NameError("name 'reio_camb' is not defined")'

Is there a way to pass these parameters that I don't know of?

Cheers,
Stefan

Edit: Passing it with **value** `'reio_parametrization': {'value': 'reio_camb'}` also gives the function interpretation `[tools] *ERROR* Failed to load external function: 'NameError("name 'reio_camb' is not defined")'`

**Comment by JesusTorrado** [comment]
Hi Stefan,

Non-float parameters for theory codes should be passed via the "extra_args" option of each theory code.

(Sorry for having been disconnected).

Closing this one, since it's trivial.
