### ISSUE TITLE
info dictionaries cannot be reused

### ISSUE THREAD

**Issue by cmbant** [CobayaSampler/cobaya#52]
We know about this already internally, just putting it on the public list so it's out there: testing using model = get_model(info) and then using cobaya.run(info) does not work (currently have to make new clean info dictionary before calling cobaya.run(info). This is easy to do when testing in Jupyter, cf.
https://cosmocoffee.info/viewtopic.php?f=11&t=3244

**Comment by JesusTorrado** [comment]
This appears to be working now, right?

**Comment by cmbant** [comment]
Doesn't work on master or external_modules branch, but this example at least does seem OK on devel (using tuple for interpolator index). I didn't do anything aimed specifically at fixing this though!

**Comment by cmbant** [comment]
I moved the deepcopywherepossible to the top in get_model and a trival change elsewhere so I think this is now fixed with https://github.com/CobayaSampler/cobaya/commit/cf2c48d5ddb4b9ee28acf4a57ace3f448b58c2bd on devel (unless there are possible issues with things that can't be deepcopied)
