### ISSUE TITLE
Installation of external modules

### ISSUE THREAD

**Issue by xgarrido** [CobayaSampler/cobaya#59]
I would like to make an external likelihood such as https://github.com/simonsobs/LAT_MFLike, able to download its data (from this directory https://github.com/simonsobs/LAT_MFLike_data). So far I have changed the MFLike likelihood declaration to make it inherits from ```_InstallableLikelihood``` (see my try [here](https://github.com/simonsobs/LAT_MFLike/blob/feature-installable-data/mflike/mflike.py)). 

When I do ```cobaya-run``` with a slightly modified version of this [file](https://github.com/simonsobs/LAT_MFLike/blob/feature-installable-data/tests/test_mflike.yaml) (no ```python_path``` for instance) everything runs fine. But when I do ```cobaya-install```, it tells me 

```
[install] *ERROR* Module 'mflike.MFLike' not recognized. [No module named 'cobaya.likelihoods.mflike']

[install] *ERROR* The installation (or installation test) of some module(s) has failed: 
 - likelihood:mflike.MFLike
Check output of the installer of each module above for precise error info.
```

If I copy-paste the MFLike directory into the likelihoods directory of cobaya, I can make it work by changing the name of the file (!!) from ```mflike.py``` to ```MFLike.py``` and by cleaning ```__init__.py``` to make it empty. 

Of course, all this stuff is related to the PR #53. Any advice on what's going on ?

**Comment by cmbant** [comment]
I hadn't tested or updated the install code yet.. I've now had a go, try the devel branch?

**Comment by xgarrido** [comment]
The ```devel``` branch works fine. I will continue to work on this branch.
