### ISSUE TITLE
Inconsistent CMB temperature values between cobaya and CAMB/CLASS

### ISSUE THREAD

**Issue by xgarrido** [CobayaSampler/cobaya#62]
The CMB temperature value from `cobaya` [conventions file ](https://github.com/CobayaSampler/cobaya/blob/master/cobaya/conventions.py#L96) is not exactly the same as the value from CAMB or CLASS. Computed Cl between CAMB via `cobaya` and CAMB alone will then be shifted by a small amount due to the way `cobaya` rescales spectra given the [units used](https://github.com/CobayaSampler/cobaya/blob/master/cobaya/theories/camb/camb.py#L593). Either the value in conventions file matches the 2.7255 value in CAMB/CLASS or each theory wrapper get the value from CAMB or CLASS to make them self-compatible.

**Comment by cmbant** [comment]
Thanks, fixed in devel branch to camb value.
