### ISSUE TITLE
Avoid trying to import MPI for installing

### ISSUE THREAD

**Issue by timothydmorton** [CobayaSampler/cobaya#64]
In the process of ensuring that it only runs on one MPI instance, the install script currently attempts to `from mpi4py import MPI`.  If mpi4py is not available, this is all well and good, as the try/except works as intended.  However, if trying to run `cobaya-install` from a system that has mpi4py but is disallowed from using it (e.g., the head nodes at NERSC), then `cobaya-install` fails because `from mpi4py import MPI` throws a fatal error that aborts the script, rather than simply raising an exception.  

It appears that moving `from cobaya.mpi import am_single_or_primary_process` further inside the script, protected by a '--no-mpi' argument check (e.g.) should work.  Happy to make a PR for this.

**Comment by timothydmorton** [comment]
Should I base this PR off master or the 'temp' branch?

**Comment by timothydmorton** [comment]
I see this issue has its tentacles in multiple places (i.e., wherever `am_single_or_primary_process` is called); I'm looking into it.

**Comment by cmbant** [comment]
Thanks, merged in temp. I'd use devel for PRs unless specific to something being developed in a temporary side branch.
