### ISSUE TITLE
API change request to expose model likelihoods

### ISSUE THREAD

**Issue by msyriac** [CobayaSampler/cobaya#72]
When a new model is built with
```
model = get_model(info)
```

it is useful to have the underlying likelihoods exposed to the user. An example where I needed this was to generate mock BAO likelihood data for pipeline verification. The BAO likelihood has a useful `theory_fun` (e.g. to get DM_over_rs) which I didn't want to duplicate. It was not obvious through a cursory tab completion search in iPython on `model.likelihood` where I could access the underlying likelihood objects, and I had to dig through the code to find that it could be accessed through e.g:

```
thfn = model.likelihood._likelihoods['bao.sdss_dr12_consensus_bao'].theory_fun                                                                                                                
```

Attributes with an underscore in front of them are not discoverable through tab completion (unless an underscore is explicitly prefixed), so I recommend that the underscore be removed.

If there was a better way to access that underlying theory function, do let me know.

**Comment by msyriac** [comment]
UPDATE:
It appears more changes are needed to expose those functions in a usable way. (Either that, or I'm taking unnecessarily convoluted steps).

If the above theory function is used, one gets:
```
Traceback (most recent call last):
  File "gen_bao.py", line 38, in <module>
    print(thfn(z,obs))
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.0.3-py3.6.egg/cobaya/likelihoods/_base_classes/_bao_prototype.py", line 284, in theory_fun
    val = (1 + z) * self.theory.get_angular_diameter_distance(z) / self.rs()
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.0.3-py3.6.egg/cobaya/theories/camb/camb.py", line 627, in get_angular_diameter_distance
    return self._get_z_dependent("angular_diameter_distance", z)
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.0.3-py3.6.egg/cobaya/theories/camb/camb.py", line 616, in _get_z_dependent
    return np.array(deepcopy(self.current_state()[quantity]))[i_kwarg_z]
KeyError: 'angular_diameter_distance'
```

because the underlying theory calls have not been made. So to get it to work, I needed to do:
```
model = get_model(info)                                                                                                                                                                       
updated_info, products, sampler = run(info)                                                                                                                                                  
thfn = sampler.model.likelihood._likelihoods['bao.sdss_dr12_consensus_bao'].theory_fun
```
where the `Evaluate` sampler is used at the cosmology I wanted the mock BAO data at. Note that I had to edit cobaya.run.run() to return the `sampler` object as well, since currently it only returns `updated_info` and `sampler.products`.

**Comment by cmbant** [comment]
If you could base off devel that would be helpful - there are a lot of changes since the sources branch.

**Comment by msyriac** [comment]
Ok, the devel branch does seem to allow me to access the likelihood with:
```
sampler.model.likelihood['bao.sdss_dr12_consensus_bao'].theory_fun
```

However, I still need the full sampler object to be returned from `run()`. Is it still useful to have a PR that just adds the possibility of returning the full sampler object like this?
```
updated_info, products, sampler = run(info,return_sampler=True)                                                                                                                              
```

**Comment by cmbant** [comment]
Can't you just access model.likelihood obtained from get_model?

**Comment by msyriac** [comment]
Here's the error I get if I try to use model.likelihood from get_model:
```
> thfn = model.likelihood['bao.sdss_dr12_consensus_bao'].theory_fun 
> thfn(0.38,'DM_over_rs')

[model] *WARNING* Ignored blocks/options: ['force', 'sampler']
[prior] *WARNING* No sampled parameters requested! This will fail for non-mock samplers.
[camb] Importing *global* CAMB.
[bao.sdss_dr12_consensus_bao] Initialising.
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "gen_bao.py", line 39, in <module>
    val = thfn(z,obs)[0]
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.1.0-py3.6.egg/cobaya/likelihoods/_base_classes/_bao_prototype.py", line 290, in theory_fun
    return (1 + z) * self.theory.get_angular_diameter_distance(z) / self.rs()
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.1.0-py3.6.egg/cobaya/theories/_cosmo/boltzmannbase.py", line 205, in get_angular_diameter_distance
    return self._get_z_dependent("angular_diameter_distance", z)
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.1.0-py3.6.egg/cobaya/theories/camb/camb.py", line 573, in _get_z_dependent
    return np.array(self._current_state[quantity], copy=True)[i_kwarg_z]
AttributeError: 'camb' object has no attribute '_current_state'
-------------------------------------------------------------
```

It looks like some of the calculations are not done until model is passed through run().

**Comment by cmbant** [comment]
You do need to call logposterior or similar first to actually calculate something for given parameters, see examples at

https://cobaya.readthedocs.io/en/devel/cosmo_model.html#using-the-model-wrapper

**Comment by msyriac** [comment]
OK, that works, thanks!
