### ISSUE TITLE
Post-processing with derived parameters

### ISSUE THREAD

**Issue by evanmcdonough03** [CobayaSampler/cobaya#76]
Hi,

I am experimenting with post-processing of basic cosmology runs, using the shell, and I have a confusion regarding specifying a likelihood for a derived parameter. Perhaps I am missing a small piece of the syntax; any thoughts or comments would be appreciated.

This is related to issue #18, and to Jesus’ comment,

Another alternative: add the following likelihood (likelihoods are evaluated after the theory code)

omb: "lambda _theory={'omegam': None}: np.log(0 <= _theory.get_param('omegam') <= 1)"

The above can be implemented as a likelihood in an “add” block in post. For example,

output: chains/test
post:
  suffix: sigma8
  add:
    likelihood:
      sigma8likelihood: "lambda _theory={'sigma8': None}: np.log(0 <=_theory.get_param('sigma8') <= .81)"

However, this causes Cobaya to recompute the theory code for every sample, even when sigma8 has already been computed and is stored in the chain.  By design, the ‘recompute’  doesn’t actually compute any derived parameters (unless they have been explicitly “added”), and I believe the sigma8 value it uses is simply that read in from the chain. The same applies to applying a likelihood on any other derived parameter.

This leads to a severe slow-down of post-processing. Is there any way to add a likelihood for a derived parameter (in post), without Cobaya recomputing the theory code?

This situation is supposedly prevented by line 180 of Cobaya's post.py, but that doesn’t seem to be having any effect.

Thanks,
Evan

**Comment by cmbant** [comment]
https://github.com/CobayaSampler/cobaya/pull/160 should fix this.

**Comment by cmbant** [comment]
Now merged to master
