### ISSUE TITLE
Getting likelihood directly from Cls

### ISSUE THREAD

**Issue by heatherprince** [CobayaSampler/cobaya#78]
Does Cobaya currently support passing Cls as arrays directly to the Planck likelihood without using a theory function? I would find this really useful, maybe within the model wrapper.

**Comment by JesusTorrado** [comment]
Hi @heatherprince 

Not directly. As is, you would have to create your own ``theory``, which I assume you are trying to do, given #79 (or maybe import clik and call it yourself directly? or use the already-imported instance at ``model.likelihood["whichever planck like"].clik``?).

I will give it a thought though, since it may be useful for other likelihoods too.

**Comment by cmbant** [comment]
You can do it with some of the native likelihoods, but not the plik ones. e.g. TT_lite_native has a "chi_squared" function that just takes in an array of CL. Likewise the native lensing likelihood (and BK15 and others based on CMBlikes) have a log_likelihood() in terms of cls.

I've certainly been encouraging people writing new likelihood classes to structure it this way, so they can wither be called via Cobaya (in terms of parameters), or instantiated directly and called with an observable independently of the rest of Cobaya.

If you want to do it with plik it may be as simple as changing the current "logp" in _planck_clik_prototype to
```
    def logp(self, **params_values):
        # get Cl's from the theory code
        cl = self.theory.get_Cl(units="muK2")
        return self.log_likelihood(cl, **params_values)

    def log_likelihood(self, cl, **params_values):
        # fill with Cl's
        self.vector[:-len(self.expected_params)] = np.concatenate(
            [(cl[spectrum][:1 + lmax] if spectrum not in ["tb", "eb"]
              else np.zeros(1 + lmax))
             for spectrum, lmax in zip(self.requested_cls, self.l_maxs_cls)])
        # fill with likelihood parameters
        self.vector[-len(self.expected_params):] = (
            [params_values[p] for p in self.expected_params])
        loglike = self.clik(self.vector)[0]
        # "zero" of clik
        if np.allclose(loglike, -1e30):
            loglike = -np.inf
```

**Comment by heatherprince** [comment]
Rewriting logp to include the option to take Cl's was exactly what I needed, thank you!
