### ISSUE TITLE
Documentation for using external theory codes

### ISSUE THREAD

**Issue by heatherprince** [CobayaSampler/cobaya#79]
I am a new Cobaya user and have found it challenging to get my external theory code to interface with Cobaya. I would really appreciate more complete documentation on this.

**Comment by cmbant** [comment]
Is this regarding the devel branch? (should use devel for this)
e.g. what would you like in addition to what's at
https://cobaya.readthedocs.io/en/devel/theories_and_dependencies.html
https://cobaya.readthedocs.io/en/devel/theory.html
https://cobaya.readthedocs.io/en/devel/likelihoods.html#implementing-your-own-external-likelihood-class

**Comment by heatherprince** [comment]
I'm not sure if this is mentioned somewhere in the docs and I missed it but I didn't realise I needed to be using the devel branch for external theory codes until you replied to my cosmocoffee question, so I think it would be good to have that information either in the docs or the usage section of external.py. When I was looking through the 'theories' folder and found external.py I got the impression I could use the version of cobaya that I installed with pip and interface an external theory code with external. I still need to give this a go using the devel branch so I will see how I do with the documentation you have linked.

**Comment by cmbant** [comment]
Yes, devel is not linked from master yet, sorry about confusion. We hope to have it merged and released in a couple of weeks (however we've also been saying that for some months..)

**Comment by cmbant** [comment]
Version 3 is now released on master, so closing. Now
https://cobaya.readthedocs.io/en/latest/theories_and_dependencies.html
https://cobaya.readthedocs.io/en/latest/theory.html
https://cobaya.readthedocs.io/en/latest/likelihoods.html#implementing-your-own-external-likelihood-class
