### ISSUE TITLE
w0-wa

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#8]
Hi 

How can enable w0-wa parameterization? (I need to run some chains to DES meeting in 2 weeks).

Best
Vivian

**Comment by cmbant** [comment]
Use the devel CAMB branch. However currently this is super slow compiled with ifort (fine with gfortran). Intel are investigating why. If you use 0cb73635548d3c7a81afbf3cc90bb651891ac312 it should be OK (also better tested).

**Comment by JesusTorrado** [comment]
Added in 1.1 (commit cccb5f4f3d42345d)
