### ISSUE TITLE
cobaya-run overrides "resume" key in yaml

### ISSUE THREAD

**Issue by msyriac** [CobayaSampler/cobaya#81]
Maybe this is intended behaviour but that was not obvious from the documentation:
![2020-03-03_09:28:26](https://user-images.githubusercontent.com/3674397/75785254-7111e400-5d31-11ea-8037-98352f3f05ac.png)
https://cobaya.readthedocs.io/en/latest/input.html#running-cobaya

i.e. currently cobaya-run does not care whether "resume: True" exists in the yaml file, it only resumes if the "--resume" option is provided.

**Comment by JesusTorrado** [comment]
Totally not intended, sorry. Are you using `master`, `devel` or have you installed via pip?

**Comment by msyriac** [comment]
I'm using devel.

**Comment by JesusTorrado** [comment]
Fixed in a0ff13a. Sorry for the delay and thanks for the issue!
