### ISSUE TITLE
Native Planck Likelihood

### ISSUE THREAD

**Issue by jakehelton** [CobayaSampler/cobaya#82]
Hi, 

I am a new cobaya user trying to get the likelihood planck_2018_highl_plik.TTTEEE_lite_native working but I'm running into the following error: 

"The data file 'plik_lite_v22.dataset' could not be found... Either you have not installed this likelihood, or have given the wrong modules installation path."

I've made sure that it's not automatically installed in a different path and I've also looked for this data file or one similar to it in the cobaya github, but have had no luck. Any help with this would be great.

Thanks!
Jake

**Comment by cmbant** [comment]
If you are using the latest devel branch you can use 

cobaya-install -p /path/for/packages planck_2018_highl_plik.TTTEEE_lite_native

to install the relevant files.

**Comment by jakehelton** [comment]
That seems to have worked, thank you!
