### ISSUE TITLE
Need both Linear and Non-linear PS

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#86]
Hi Jesus,

I hope you are safe and healthy in these difficult times. I write because while implementing Cobaya-Cosmolike for DES-Y3 - we saw that Cobaya has no option to provide to the DES likelihood the linear and non-linear power spectrum at the same time. We need that for the non-limber calculation. Can you help us?

**Comment by cmbant** [comment]
Try using the devel branch (hopefully very soon to be released). If you request the non-linear Pk_grid or Pk_interpolator you can then get both the linear and non-linear spectrum.

**Comment by vivianmiranda** [comment]
Thank you! I will try it now

**Comment by vivianmiranda** [comment]
Question - how do we ask for linear and non-linear interpolator in that case?

**Comment by cmbant** [comment]
Just request with Pk_grid or Pk_interpolator with nonlinear:True option (from get_requirements). The docs should be up to date (eg. https://cobaya.readthedocs.io/en/devel/theory_camb.html).

**Comment by vivianmiranda** [comment]
Thanks

I see it now.

I also saw that you disable the possibility of sending k in h units and returning of returning PS in h units. Is it possible to add them back in as options in get_Pk_interpolator?

Best
Vivian

On Apr 14, 2020, at 11:29 AM, Antony Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


External Email


Just request with Pk_grid or Pk_interpolator with nonlinear:True option (from get_requirements). The docs should be up to date (eg. https://cobaya.readthedocs.io/en/devel/theory_camb.html).

**Comment by cmbant** [comment]
It would be possible, but I think it's generally clearer not to confuse things with odd units - should be simple to convert the output if you want to.

**Comment by vivianmiranda** [comment]
Sorry for bothering you again - but I tried

`
PKL = self.theory.get_Pk_interpolator(("delta_tot", "delta_tot"),
                               nonlinear=False, extrap_kmax = 160000 * self.acc)

    # Compute non-linear matter power spectrum
    PKNL = self.theory.get_Pk_interpolator(("delta_tot", "delta_tot"),
                                nonlinear=True, extrap_kmax = 160000 * self.acc)
`

and then I got the error 

`
[camb] *ERROR* Matter power delta_tot, delta_tot not computed
`

My needs function is the following

`
return {
      "H0": None,
      "omegam": None,
      "Pk_interpolator": {
        "z": self.z_interp_2D, 
        "k_max": 15 * self.acc,
        "nonlinear": True,
        "vars_pairs": ([("delta_tot", "delta_tot")])
      },
      "comoving_radial_distance": {
        "z": self.z_interp_1D
      # Get comoving radial distance from us to redshift z in Mpc. 
      }
    }
`

**Comment by cmbant** [comment]
Maybe you're right - need to request nonlinear:(True,False) to be able to get both?

**Comment by vivianmiranda** [comment]
Yes - that worked

Thanks :)

Stay safe!

On Apr 14, 2020, at 2:10 PM, Antony Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:

(True,False)

**Comment by cmbant** [comment]
https://github.com/CobayaSampler/cobaya/commit/410efe4ff3b5ca837ad14ad87dcd74ffb878509a updates doc
