### ISSUE TITLE
Cosmological parameters with camb & class

### ISSUE THREAD

**Issue by adrien-laposta** [CobayaSampler/cobaya#87]
Hi

I'm trying to do some Simons Obs. mcmc forecasts  for the 6 standard  cosmo. parameters but have significantly different posterior distributions with Camb or Class
![forecast_mcmc_compared_v2](https://user-images.githubusercontent.com/61697123/79335274-094edb80-7f22-11ea-915b-b85ecb69c28b.png)

Here you can find the .yaml files used in the mcmc
[forecast_camb.txt](https://github.com/CobayaSampler/cobaya/files/4481084/forecast_camb.txt)
[forecast_class.txt](https://github.com/CobayaSampler/cobaya/files/4481086/forecast_class.txt)

Do you have any config. that could help to reduce the difference between the two codes ?
Thanks,
Adrien

**Comment by cmbant** [comment]
Well I guess you are using different halofit models (unless class defaults to hmcode), and possibly also BBN models unless you checked that. I would also first check that each code separately gives stable chi2 under variation of the accuracy parameters, e.g. for CAMB you may need lens_potential_accuracy > 1 (you don't say if you are including lensing or not - which SO likelihood is this?). Do you really need max_l: 9000?

You can use the [gui](https://cobaya.readthedocs.io/en/devel/cosmo_basic_runs.html) to view default configs for CAMB and class with Planck likelihoods, and adjust.

**Comment by adrien-laposta** [comment]
Hi, thanks for your answer

I checked the defaults for bbn and halofit, using HMcode instead of nothing in class does not change anything. (I used the GUI to build the theory blocks used in my mcmc). 
I have changed accuracy parameters for camb and the relative chi2 variation is ~0.6%.
Concerning the likelihood:  I am working on a simple likelihood for a m2 internship with TT-EE-TE only (but the spectra are lensed). I need multipoles from 2 to 4500, thus I put a high max_ell because I noticed that the difference between class&camb at high multipole is very dependent on this ell_max

**Comment by cmbant** [comment]
Are you using the latest devel branch? Probably best to start by comparing the spectra for fixed cosmological parameters and see if they agree as expected over the relevant ell. See e.g. (using devel branch)
https://cobaya.readthedocs.io/en/devel/cosmo_model.html

**Comment by cmbant** [comment]
I'll close this assuming now OK
