### ISSUE TITLE
I can't run mpirun np X Cobaya-run input.yaml with Polychord

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#9]
with X > 1 (with X=1 I can run) - it seems that MPI in Cobaya and Polychord are not talking

I attached the debug output file

[file.txt](https://github.com/CobayaSampler/cobaya/files/2623117/file.txt)

Thank you a lot for helping me one more time!! You two are the best!

Best Regards
Vivian Miranda

**Comment by JesusTorrado** [comment]
After a second look, I am more inclined to think that this is a race condition, so if the 1st solution does not work (please, check it out anyway), try the following: substitute the 1st 4 lines of code in the `run_polychord` function in `PolyChord/PyPolychord/__init__.py` with

        try:
            from mpi4py import MPI
            comm = MPI.COMM_WORLD
            rank = comm.Get_rank()
        except ImportError:
            rank = 0

        if not os.path.exists(settings.base_dir) and rank == 0:
            os.makedirs(settings.base_dir)

        if not os.path.exists(settings.cluster_dir) and rank == 0:
            os.makedirs(settings.cluster_dir)

I am going to submit an issue to the official PolyChord repo.

**Comment by vivianmiranda** [comment]
It is indeed a race condition...your change of code fixed!
