### ISSUE TITLE
Question on multi threading with cobaya, using classy

### ISSUE THREAD

**Issue by borisbolliet** [CobayaSampler/cobaya#93]
Hi,

I am using classy as the Boltzmann code and if i understand correctly when I launch:

$ cobaya-run input.yaml

each evaluation by classy is done on one thread only. While when I call (externally from cobaya):

>> cosmo.compute() 

with the same classy, one evaluation is done by the 8 threads available on my computer. 

Is there a way I can set the number of threads within cobaya, that will be available for each classy evaluation? That would reduce significantly the time/evaluation.

Or maybe I am just missing something in the input file to simply tell cobaya to use classy with openmp?

Thanks a lot,
Boris

**Comment by JesusTorrado** [comment]
Hi Boris,

That's definitely unintended. Will investigate. Thanks for the report!

**Comment by JesusTorrado** [comment]
Ah, what I was suspecting: CLASS runs *mostly* parallelized, but for some reason the `hmcode` computation doesn't. I've open an issue in CLASS (see link above)

**Comment by borisbolliet** [comment]
Hi Jesus,

Thanks a lot for the fast response. 

Using current version of cobaya and classy (as installed with cobaya-install cosmo), with Anaconda3's python, it seems to me that the issue is related to the OMP environment variables and function, as treated by cobaya. 

For instance, the k-loop in the perturbation module (independent of HM code) is parallelised in class by calling

```
#ifdef _OPENMP

#pragma omp parallel
  {
    number_of_threads = omp_get_num_threads();
  }
#endif
```

If we ask for perturbations_verbose >=3, and do cosmo.compute()

we get:

```
In perturb_init: time spent in parallel region (loop over k's) = 3.271490e+00 s for thread 5
In perturb_init: time spent in parallel region (loop over k's) = 3.278081e+00 s for thread 6
In perturb_init: time spent in parallel region (loop over k's) = 3.274073e+00 s for thread 3
In perturb_init: time spent in parallel region (loop over k's) = 3.278263e+00 s for thread 0
In perturb_init: time spent in parallel region (loop over k's) = 3.281111e+00 s for thread 1
In perturb_init: time spent in parallel region (loop over k's) = 3.275317e+00 s for thread 2
In perturb_init: time spent in parallel region (loop over k's) = 3.274579e+00 s for thread 4
In perturb_init: time spent in parallel region (loop over k's) = 3.280962e+00 s for thread 7
```

meaning the parallelisation seems fine, running on 8 threads. 

However when we do the same, but calling classy via cobaya, we just get

`In perturb_init: time spent in parallel region (loop over k's) = 5.726378e+00 s for thread 0`

meaning the parallelisation is not fine and classy uses only one thread. 

If we do:

printf("%d\n",number_of_threads);

just before the k-loop in perturbations.c, running classy on its own, we find number_of_threads=8. But with cobaya, we find number_of_threads=8.

That means that for some reason, in cobaya, omp_get_num_threads() does not return the maximum number of available threads.

**Comment by borisbolliet** [comment]
Hi Jesus,

I just ran the same on Linux (I was running on a mac previously), and now the code runs well on multi threads. That's great.

So it seems the issue is specific to mac (or at least to my mac).  

I close the issue for now and will remember of updating if I understand what happens on my mac that is different with Linux. 

Thanks a lot for the help and apologise in case that is just due to my own config on my laptop,
Cheers,
Boris

**Comment by borisbolliet** [comment]
Hi,

I still have this issue on a different mac... I have been trying to figure out what could cause this, but didn't manage so far. 

I am sure it is not a classy problem, because when I do: class.compute() in a python terminal (independently of cobaya), classy runs on the 8 threads. As I explained initially. 

Anyway, this is not crucial as we rarely need to run mcmc's on mac and hopefully the issue will disappear at the new macOS release or next anaconda update. 

But if anyone has had the same problem and found a solution I would be very happy to know what to do.

Thanks a lot,
Boris

**Comment by borisbolliet** [comment]
I think I found a solution to this:

$ rm  /path/to/anaconda3/lib/libgomp.*

There seemed to be a problematic confusion between the libgomp libraries stored in the directory anaconda3/lib and those stored in /usr/local/lib/gcc/10/. 
Removing libgomp.a, libgomp.dylib, libgomp.a and libgomp.spec from anaconda3/lib solves the problem and now class runs properly in parallel. 

This is most certainly a MacOS and anaconda specific problem.

Thanks a again for the help!

**Comment by cmbant** [comment]
There's  a similar CAMB-compiling issue on linux in
https://travis-ci.org/github/CobayaSampler/cobaya/jobs/754867526
when building with gcc10 and anaconda (libgfortran.so.5: version `GFORTRAN_10' not found). I assumed this was some misconfiguration (or non-updatedness) of anaconda
