### ISSUE TITLE
Add option to prefer globally installed dependency over cobaya-installed one

### ISSUE THREAD

**Issue by timothydmorton** [CobayaSampler/cobaya#94]
I am planning to use cobaya from within different conda envs that will have different versions of Boltzmann codes installed.  However, I have just discovered that the first place cobaya will look for, e.g., classy is in `load_config_file().get(_packages_path)`.  The fact that `load_config_file()` returns a system-wide global file undermines the expected behavior of a conda environment, as I would have expected the python-system-installed classy (e.g., the environment version) to take precedence.  I know there are ways to work around this, but just wanted to bring it to attention, as I can imagine this might be a commonly desired use model (e.g., using environments to keep different projects separate, and not wanting to have to explicitly give the in-env classy install path).

**Comment by timothydmorton** [comment]
One way to ameliorate this might be to write the config file (which presumably gets created when `cobaya-install cosmo` is run) to an environment specific file, e.g., if `$CONDA_PREFIX` exists.

**Comment by timothydmorton** [comment]
Or to have a way to say `path = 'global'`, or equivalent, within the model definition.

**Comment by cmbant** [comment]
I think the intention is that you have different versions of codes in different paths, then explicitly give the python_path when you assign the theory in the yaml. I think normally this works better, as e..g you can then debug directly in the modified source when developing rather than having to install each time. An explicit python_path should take preference over any other defaults.

**Comment by cmbant** [comment]
But I agree some way to make it use the env-installed version might be useful.

**Comment by JesusTorrado** [comment]
Hi @timothydmorton and @cmbant 

With the code as is, you can already signal different installation paths per environment using the `COBAYA_PACKAGES_PATH` env, which takes preference over the config file. Would that be enough (and practical enough) for what you intend to do?

As for having a different config file per environment, we could do that, but as far as I have looked around, there is no standard way to define where this file would be placed, right?

`path = 'global'` is something we have discussed about at some point, I think, and it would make sense. I'll add it to #92, if Antony agrees.

**Comment by timothydmorton** [comment]
I like `path = 'global'`.  It's a simple way to just flip the priority.  I'd like the following workflow:

* Activate env
* build custom version of class from command line (which installs classy to env/site-packages)
* have an easy & portable way to tell cobaya to prioritize the python-installed "global" classy over anything else

**Comment by JesusTorrado** [comment]
Thanks for the clarification!

>     * build custom version of class from command line (which installs classy to env/site-packages)

This means "not using the installer", right?

**Comment by timothydmorton** [comment]
Yes, that's what I meant; i.e., go to the class dir and run `make`.

**Comment by JesusTorrado** [comment]
Almost finished with #92. Now, after manually installing CLASS you will have two options:

a) install the rest of the dependencies with `cobaya-install --skip-global` (will ignore CLASS); no `path: global` needed in this case.
b) Install without `--skip-global` (will install CLASS locally), and add `path: global` to classy to prefer global Python package.

Both already work in #92 , if you'd like to try it (but no need to).

**Comment by JesusTorrado** [comment]
#92 has been merged. The two possible pipelines above would IMO fulfill your needs. Closing (but please feel free to re-open if this is not enough, or it doesn't work as expected!).

**Comment by timothydmorton** [comment]
just got around to testing this with `path: global` and seems to work, thanks!
