### ISSUE TITLE
Issue in number of chain files

### ISSUE THREAD

**Issue by surgithub** [CobayaSampler/cobaya#96]
Hi, I am new to cobaya.

The command
`mpirun -np 4 cobaya-run planck1.yaml -p cobaya_packages`
initiates 4 instances of mpi, and runs fine. But in the output folder, I see only one chain file. 

Thanks.

**Comment by cmbant** [comment]
Could you try with "mpi_warnings" branch, where I tried to add some error checks, and see if that give a more helpful error ?

@JesusTorrado, this has come up a few times in multiple guises. Do you think the check at https://github.com/CobayaSampler/cobaya/blob/mpi_warnings/cobaya/collection.py#L349 is safe (or better place to try to check exclusive write on each chain output)?

**Comment by surgithub** [comment]
As mentioned earlier, it initiates 4 instances of mpi and runs fine without displaying any errors. I notice that all the accepted samples of four different samplings are written in one chain file. So I think the code needs some correction for writing the accepted samples in four different chain files. Thanks.

**Comment by cmbant** [comment]
Did you install and run in the mpi_warnings branch?

**Comment by surgithub** [comment]
Yes. I did that. Still the output is going to only one chain file. Following is the onscreen output. 

`mpirun -np 2   cobaya-run planck.yaml -p cobaya_packages -o trial/sk
--------------------------------------------------------------------------
[[43768,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: hn001

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
[[43771,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: hn001

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
[output_mpi] Output to be read-from/written-into folder 'trial', with prefix 'sk'
[output_mpi] Output to be read-from/written-into folder 'trial', with prefix 'sk'
[prior] *WARNING* External prior 'SZ' loaded. Mind that it might not be normalized!
[classy] Importing *local* classy from /home/hpadmin/cobaya_packages/code/classy
[bao.sixdf_2011_bao] Initialising.
[bao.sdss_dr7_mgs] Initialising.
[bao.sdss_dr12_consensus_bao] Initialising.
[planck_2018_lowl.tt] Importing clik from cobaya_packages/code/planck
[prior] *WARNING* External prior 'SZ' loaded. Mind that it might not be normalized!
[classy] Importing *local* classy from /home/hpadmin/cobaya_packages/code/classy
[bao.sixdf_2011_bao] Initialising.
[bao.sdss_dr7_mgs] Initialising.
[bao.sdss_dr12_consensus_bao] Initialising.
[planck_2018_lowl.tt] Importing clik from cobaya_packages/code/planck
[mcmc] Getting initial point... (this may take a few seconds)
[mcmc] Getting initial point... (this may take a few seconds)
[model] Measuring speeds... (this may take a few seconds)
[model] Measuring speeds... (this may take a few seconds)
[model] Setting measured speeds (per sec): {bao.sixdf_2011_bao: 3960.0, bao.sdss_dr7_mgs: 6350.0, bao.sdss_dr12_consensus_bao: 3740.0, planck_2018_lowl.TT: 3760.0, planck_2018_lowl.EE: 5910.0, planck_2018_highl_plik.TTTEEE: 30.4, planck_2018_lensing.clik: 488.0, classy: 0.0922}
[mcmc] Dragging with number of interpolating steps:
[mcmc] *  1 : [['logA', 'n_s', 'theta_s_1e2', 'omega_b', 'omega_cdm', 'tau_reio']]
[mcmc] * 32 : [['A_planck'], ['calib_100T', 'calib_217T', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217']]
[model] Setting measured speeds (per sec): {bao.sixdf_2011_bao: 3870.0, bao.sdss_dr7_mgs: 6110.0, bao.sdss_dr12_consensus_bao: 3570.0, planck_2018_lowl.TT: 3610.0, planck_2018_lowl.EE: 5600.0, planck_2018_highl_plik.TTTEEE: 28.6, planck_2018_lensing.clik: 474.0, classy: 0.093}
[mcmc] Dragging with number of interpolating steps:
[mcmc] *  1 : [['logA', 'n_s', 'theta_s_1e2', 'omega_b', 'omega_cdm', 'tau_reio']]
[mcmc] * 32 : [['A_planck'], ['calib_100T', 'calib_217T', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217']]
[mcmc] Covariance matrix selected automatically: {packages_path}/data/planck_supp_data_and_covmats/covmats/base_plikHM_TTTEEE_lowl_lowE_lensing_post_BAO.covmat
[mcmc] Covariance matrix loaded for params ['omega_b', 'omega_cdm', 'tau_reio', 'logA', 'n_s', 'A_planck', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217', 'calib_100T', 'calib_217T']
[mcmc] Missing proposal covariance for params ['theta_s_1e2']
[mcmc] Covariance matrix not complete. We will start learning the covariance of the proposal earlier: R-1 = 30 (would be 2 if all params loaded).
[mcmc] Initial point: logA:3.050587, n_s:0.9594358, theta_s_1e2:1.042256, omega_b:0.02233923, omega_cdm:0.1226683, tau_reio:0.05721401, A_planck:1.000129, calib_100T:0.9992458, calib_217T:0.9966404, A_cib_217:59.81557, xi_sz_cib:0.07789728, A_sz:5.503001, ksz_norm:4.076807, gal545_A_100:6.593299, gal545_A_143:10.60794, gal545_A_143_217:18.86943, gal545_A_217:76.52262, ps_A_100_100:275.2867, ps_A_143_143:42.03551, ps_A_143_217:31.75419, ps_A_217_217:115.4974, galf_TE_A_100:0.09869295, galf_TE_A_100_143:0.2188325, galf_TE_A_100_217:0.3770747, galf_TE_A_143:0.1626859, galf_TE_A_143_217:0.6520706, galf_TE_A_217:2.153084
[mcmc] Covariance matrix selected automatically: {packages_path}/data/planck_supp_data_and_covmats/covmats/base_plikHM_TTTEEE_lowl_lowE_lensing_post_BAO.covmat
[mcmc] Covariance matrix loaded for params ['omega_b', 'omega_cdm', 'tau_reio', 'logA', 'n_s', 'A_planck', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217', 'calib_100T', 'calib_217T']
[mcmc] Missing proposal covariance for params ['theta_s_1e2']
[mcmc] Covariance matrix not complete. We will start learning the covariance of the proposal earlier: R-1 = 30 (would be 2 if all params loaded).
[mcmc] Initial point: logA:3.050737, n_s:0.9676396, theta_s_1e2:1.041332, omega_b:0.02241242, omega_cdm:0.1212305, tau_reio:0.05539341, A_planck:1.000868, calib_100T:1.000344, calib_217T:0.9979378, A_cib_217:66.81529, xi_sz_cib:0.02869933, A_sz:7.367021, ksz_norm:1.057532, gal545_A_100:6.977242, gal545_A_143:10.23257, gal545_A_143_217:24.8589, gal545_A_217:64.56951, ps_A_100_100:250.2082, ps_A_143_143:61.04395, ps_A_143_217:41.53111, ps_A_217_217:115.2958, galf_TE_A_100:0.03507255, galf_TE_A_100_143:0.2009881, galf_TE_A_100_217:0.4835515, galf_TE_A_143:0.3124223, galf_TE_A_143_217:0.7744582, galf_TE_A_217:1.997485
[mcmc] Sampling!
[mcmc] Sampling!
[mcmc] Progress @ 2020-05-28 08:27:05 : 1 steps taken, and 0 accepted.
[mcmc] Progress @ 2020-05-28 08:27:05 : 1 steps taken, and 0 accepted.
[mcmc] Progress @ 2020-05-28 08:28:08 : 6 steps taken, and 3 accepted.
[mcmc] Progress @ 2020-05-28 08:28:12 : 9 steps taken, and 2 accepted.`

**Comment by cmbant** [comment]
I'm not sure why that branch doesn't give you a more helpful message, the tests for writing an already-existing file must be missing something but not sure what. (you checked out the  mpi_warnings  branch and then installed it?)

In any case, your issue is that it is not actually running MPI - check e.g. you have mpi4py installed and working.

**Comment by JesusTorrado** [comment]
To test that the MPI python wrapper is working correctly, and some tips on how to fix it, see
https://cobaya.readthedocs.io/en/latest/installation.html#mpi-parallelization-optional-but-encouraged

**Comment by surgithub** [comment]
Yes. Thank you very much.
