### ISSUE TITLE
Get Hessian in Minimizer

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#98]
Hello,

Is it possible to get the Hessian in Minimizer? I want to use that as input proposal matrices in chains?

Best
Vivian

**Comment by cmbant** [comment]
No. The smart quadratic minimizers like BOBYQA do build an estimate of the hessian internally, but it's generally quite sparse and not recommended for any further use (I asked Powell about this at some point before he died). One could of course add a separate FIsher-like code to estimate it, but in practice with CosmoMC I found it not very useful (hard to make robust, e.g. in the presence of nuisance parameters with hard priors near the peak and non-Gaussian posteriors - and you want the time to evaluate it to be short).

**Comment by JesusTorrado** [comment]
If you really, really want to, Cobaya returns the *result* object of both scipy.optimize and pybobyqa. In the scipy case, you'd grab it with `result["hess_inv"].todense()`, and with pybobyqa `result.hessian`.

But I completely agree with Antony that it will be a very bad estimate. Just two days ago I was chekcing it myself for another project, and even with a very gaussian likelihood it could be off by one order of magnitude with respect to the analytical one.

Getting an early covmat estimate is an open problem for us right now. At some point I tried to write a very simple elliptical nested sampler that would be run with very low precision, to get a rough estimate. But never finished it, and probably not very practical anyway.

**Comment by andreufont** [comment]
Hi @JesusTorrado - I've started to use Cobaya recently (with help by Pablo Lemos), and so far it has been (pretty) smooth sailing!

I did miss a bit of documentation on how to use the results from the minimiser, in particular how to use the Hessian to have a (simple) estimate of the covariance matrix at the best-fit. Note that I don't want it for a MCMC run. I'm working with toy examples while developing new likelihoods, and I'm 100% sure that my likelihood will be a noiseless beautiful Gaussian around the best-fit, so I just want an ellipse from the Hessian. However, I could imagine several real-case cosmological scenarios where the user knows that all parameters will be very well constrained and the Hessian would be a very useful way to do lots of tests before the final MCMC analysis. 

To be clear, I was able to access the Hessian, but I'm pretty sure they refer to the parameters internally used by the minimiser. The documentation in Cobaya mentions that you can access the affine transformation from the results object, but I couldn't figure out how to do it. @vivianmiranda, were you ever able to successfully compute the Hessian from the results of the minimiser?

**Comment by JesusTorrado** [comment]
Hi @andreufont 

Glad that you are using Cobaya!

We've linked in the docs the official documentation to the "results" objects for each method. The inverse transform is returned as `"M"` in the products. So in general, you'd get the real-space local hessian estimate as

    p = sampler.products()
    r = p["result_object"]
    try:
        # method: scipy
        inv_hess = r.hess_inv.todense()
    except:
        # method: bobyqa
        inv_hess = np.linalg.inv(r.hessian)
    import numpy as np
    print(p["M"].T.dot(inv_hess).dot(p["M"]))

Anyway, as @cmbant says, expect little robustness and in general sparsity.

**Comment by andreufont** [comment]
Thank you so much @JesusTorrado , this is exactly what I was looking for!

I just checked for this simple BAO forecast the covariance from MCMC and from the Hessian agree to ~10%, so I'll definitely keep using it for testing purposes / code development.
